### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jimlee2** [arielfaur/ionic-audio#10]
hello
sorry not sure what happened to my topic here
but I can't get it to work 
I am using ionic view to test it on my iphone but it does not play anything and the app crashes

**Comment by ascendedmasta** [comment]
Can you give us some code? I have the app working on 3 different iOS devices.

**Comment by arielfaur** [comment]
@jimlee2 it won't work with ionic view. It does not support all plugins yet. You will have to run your project with `ionic run` in order to test. 
See below:
http://docs.ionic.io/v1.0/docs/view-usage
