### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by brayands** [arielfaur/ionic-audio#100]
How can I implement this audio project in an existing project?

**Comment by sfaizanh** [comment]
@brayands see [http://arielfaur.github.io/ionic-audio/2.0/index.html](http://arielfaur.github.io/ionic-audio/2.0/index.html)

**Comment by brayands** [comment]
I have already seen it but my project is ionic v1.x

**Comment by sfaizanh** [comment]
@brayands see [http://arielfaur.github.io/ionic-audio/index.html](http://arielfaur.github.io/ionic-audio/index.html) for Ionic v1
