### ISSUE TITLE
Unable to play m3u files

### ISSUE THREAD

**Issue by joelelangovan1985** [arielfaur/ionic-audio#104]
I am trying to embed a shoutcast stream , I am not able to load it with the player, is it possible ?

**Comment by arielfaur** [comment]
I haven't tried m3u files yet. Is this Ionic 2?

**Comment by joelelangovan1985** [comment]
Yes, Its ionic 2 , Do you have any idea to create a radio player for my shoutcast ?

**Comment by codinronan** [comment]
Yes this is possible. I am doing so successfully and required no extra setup to use m3u. What is the error your are getting?

The m3u file format is incredibly unforgiving. If you have even an extra space where there shouldn't be it will fail.

**Comment by tbergeron** [comment]
Any update from original poster? Otherwise can we close this issue as it's a question and not really an "issue" with the code.
