### ISSUE TITLE
Help! Track doesnt load in android device 

### ISSUE THREAD

**Issue by kristernavi** [arielfaur/ionic-audio#107]
Everything working fine in web but when in android emulator even in real device this is happen
![image](https://cloud.githubusercontent.com/assets/12774978/24825979/41444554-1c5e-11e7-890d-3a144eced200.png)

**Comment by ozknemoy** [comment]
same story

**Comment by ozknemoy** [comment]
it is all about restriction. this song works perfect" 'http://mpsound.ru/uploads/tracks/510496811_572314412_1814582943.mp3'

**Comment by endlessz** [comment]
Me too. Everything working perfectly on web browser, but in android device It's can't play the song.

**Comment by arielfaur** [comment]
Can you please try the new version? I just upgraded the module to Ionic 3. It should work by simply removing and adding the module back again `npm install ionic-audio@3.0.0`

**Comment by tbergeron** [comment]
Any update on this from original poster? Is this still happening? Did you try to update the package?

If this isn't happening anymore please close this issue. Thanks!

**Comment by madsongr** [comment]
It´s happening again with 3.2.0

**Comment by madsongr** [comment]
Solved! It´s not adding into package.json even with `npm install ionic-audio --save`. Added it manually.
