### ISSUE TITLE
Ionic2 & how to access to seekTo() function?

### ISSUE THREAD

**Issue by tbergeron** [arielfaur/ionic-audio#108]
Hi!

I'd like to create back & skip 30 seconds buttons so I need to access the `seekTo(pos` function.

I think this used to be accessible in the Ionic1 version but I cannot seem to find a way to access it at the current version.

Any suggestions?

Thanks!

---

i.e. of my current function:

```
    back30s($event) {
        var pos = this.currentTrack.progress;
        pos = pos - 30
        if (pos >= 0) {
            this.audioProvider.seekTo(pos); // wat do?
            // this.audioProvider.current.seekTo(pos); // why u no work?
        }
    }
```

PS: These are the only functions I can access:

<img width="845" alt="screen shot 2017-04-08 at 6 00 46 pm" src="https://cloud.githubusercontent.com/assets/70296/24832776/523ec2ae-1c85-11e7-906e-31671711f640.png">

**Comment by tbergeron** [comment]
Anybody has any idea? I'm trying to use this for an upcoming cross-platform app but I cannot figure out these tiny details for the life of me. Any help would be greatly appreciated 😃  Thanks!

**Comment by arielfaur** [comment]
Hi @tbergeron ! 
The `seekTo()` method belongs to the track prototype. So first you would need to get the current track from the AudioProvider and then you get access to the seekTo method:
```
let track = this.audioProvider.tracks[this.audioProvider.current];
track.seekTo(pos)
```

**Comment by tbergeron** [comment]
@arielfaur this worked wonders! thanks!
whenever you can, would you mind looking at this question too please? https://github.com/arielfaur/ionic-audio/issues/106#issuecomment-291692181 this is also a blocking issue for me thanks a whole lot for the help I greatly appreciate it :D
