### ISSUE TITLE
Ionic 3: Type Error

### ISSUE THREAD

**Issue by airasheed** [arielfaur/ionic-audio#110]
I converted my app to Ionic 3 and ran into this issue in several places in the code with Ionic-audio:

`Typescript Error: Element implicitly has an 'any' type because type 'Window' has no index signature.`

I've attached a screen shot.

![screen shot 2017-04-16 at 3 00 05 am](https://cloud.githubusercontent.com/assets/14035318/25069778/fea5445c-2250-11e7-9e4f-9fb340d3abc8.png)

**Comment by sfaizanh** [comment]
Can you share your package.json ionic-audio version or you can temporary do this
https://github.com/arielfaur/ionic-audio/issues/103#issuecomment-290206987

**Comment by arielfaur** [comment]
I just upgraded the module to Ionic 3. It should work by simply removing and adding the module back again `npm install ionic-audio@3.0.0`

**Comment by shaks786** [comment]
Hi, I tried using ionic-audio@3.0.0 but I'm still getting the same errors

**Comment by tbergeron** [comment]
I'm not getting these errors at all. Could you try to update your package again? Is this still happening? If not could this issue be closed?

**Comment by arielfaur** [comment]
Maybe you can tell us about your environment and share some code?
