### ISSUE TITLE
iOS track freeze issue

### ISSUE THREAD

**Issue by mharini** [arielfaur/ionic-audio#111]
Hi,
I implemented ionic-audio in a ionic2/angular2 app. It worked fine on android but on iOS device, it freezes once I hit the play button and the audio is not playing.

All data(name, total-time, progress-bar) are loaded perfectly fine.I could see Playing track, Pausing track logs too. I also waited for a minute to get loaded. But nothing worked.

Can you provide a solution for this?

**Comment by mharini** [comment]
And this happens both for local audio files and server audio files with http link.

**Comment by arielfaur** [comment]
I noticed an issue on iOS. It seems that we need to hit the play button a few times in order to start playback. If I navigate away to another page and then back, then the playback starts. In any case this seems an issue with iOS and HTML Audio. I guess there isn't much I can do.
Have you tried installing the Cordova Media plugin?

**Comment by mharini** [comment]
Yes. I am using Cordova Media plugin in my application. 
Now I am trying to replicate the same functionalities using Media functions. The hard part here is getting time of audio and integrating with custom progress-bar.

**Comment by mharini** [comment]
Adding this in config.xml worked for me. But, I don't know which line in this did that.
`<allow-navigation href="*"/>
  <allow-navigation href="file://*/*" />
  <allow-intent href="*"/>
  <access origin="*"/>
  <preference name="iosPersistentFileLocation" value="Compatibility" />`

I did not do any changes with ionic-audio code or values.

**Comment by tbergeron** [comment]
So this works? Any update?

I guess this issue should be closed then?

**Comment by mharini** [comment]
It works fine for me. Closing this issue.
