### ISSUE TITLE
'audio-track' is not a known element

### ISSUE THREAD

**Issue by andrewlongdotcom** [arielfaur/ionic-audio#113]
For the life of me, I cannot get the ionic-audio component to work with my ionic project. I have followed the demo included in this repo to a T I believe, but when I just try to add the <audio-track> element to my page I get the above error (see screenshot for full error). I'm also attaching screenshots of my app.module.ts and the ts file for my page where I am trying to use the ionic-audio component.

I assume I'm just missing something that will be painfully obvious to those of you more familiar with this component.

Thanks

![capture1](https://cloud.githubusercontent.com/assets/5359380/25485311/24972880-2b23-11e7-98f4-58ffcd15a085.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5359380/25485315/28928d62-2b23-11e7-9324-13165db63faf.PNG)
![capture3](https://cloud.githubusercontent.com/assets/5359380/25485321/2d573fbe-2b23-11e7-8e06-ee744844f07d.PNG)
![capture4](https://cloud.githubusercontent.com/assets/5359380/25485328/31b39a1c-2b23-11e7-9206-20f2e38ded8a.PNG)

**Comment by andrewlongdotcom** [comment]
My issues seem to be a result of the page I was trying to use the player on being an Ionic 3 page using PageModule. I tried to get the control to work by adding ionic-audio to my page.module.ts file, but wasn't able to get it to work. I removed the @IonicPage directive from my page and the control does work.

**Comment by arielfaur** [comment]
@andrewlongdotcom I haven't tried the new lazy loading feature with ionic-audio. Since ionic-audio is its own NgModule I would have thought it should work if you simply import ionic-audio wherever you need it. But it seems it won't work that way. I would have to look into that.
