### ISSUE TITLE
background playback

### ISSUE THREAD

**Issue by iamsamwood** [arielfaur/ionic-audio#12]
Hello,

This plugin is working great for me. The only missing feature is audio playback when the app is in the background--Is this feature on the development roadmap? Thanks.

**Comment by ghammond100** [comment]
I was able to get background audio in iOS by enabling it in Xcode. Target >> Capabilities >> Background Modes. Turn the capability on, and select ‘Audio and AirPlay’. Hope that helps.

**Comment by iamsamwood** [comment]
Thank you ghammond, that worked great !

**Comment by arielfaur** [comment]
Good tip!
