### ISSUE TITLE
track src from ajax request?

### ISSUE THREAD

**Issue by scuba303** [arielfaur/ionic-audio#123]
sorry, i am more or less new to inonic. my problem: i can make the audio player work. thats fine. now i want to set the audio src dynamically from an ajax call. when i use
`  this.singleTrack = {
      src: 'https://archive.org/download/swrembel2010-03-07.tlm170.flac16/swrembel2010-03-07s1t05.mp3',
      artist: 'Stephane Wrembel',
      title: 'Stephane Wrembel Live',
      art: 'assets/img/Stephane.jpg',
      preload: 'metadata' // tell the plugin to preload metadata such as duration for this track,  set to 'none' to turn off
    };`
i can't overwrite src afterwards. if i set this.singleTrack in the ajax success, it seems to be to late.

**Comment by tbergeron** [comment]
This is related to #106. No progress so far on that, I'll keep you updated if I find anything useful.

**Comment by rdai** [comment]
Don't know if this is still relevant, almost a year later, please see #188
