### ISSUE TITLE
Property 'selectedTrack' does not exist on type 'AudioService'

### ISSUE THREAD

**Issue by drhouse7** [arielfaur/ionic-audio#130]
As in the info I tried:
```

import { AudioProvider } from 'ionic-audio';

ngAfterContentInit() {
    // get all tracks managed by AudioProvider so we can control playback via the API
    this.allTracks = this.audioProvider.tracks;
  }

  playSelectedTrack() {
    // use AudioProvider to control selected track 
    this.audioProvider.play(this.selectedTrack);
  }
  
  pauseSelectedTrack() {
     // use AudioProvider to control selected track 
     this.audioProvider.pause(this.selectedTrack);
  }
```
This is the error:
Property 'selectedTrack' does not exist on type 'AudioService'

**Comment by th3nule** [comment]
Good night, you found the solution?

**Comment by arielfaur** [comment]
@drhouse7 Have you found a solution to this issue?

**Comment by drhouse7** [comment]
@arielfaur @th3nule Sorry but I didn't investigate further, I moved to React Native.

**Comment by th3nule** [comment]
Good night, I got it sorted out. I'm going to launch a tutorial and post here!

**Comment by th3nule** [comment]
O problema é algo muito simples (que não está na documentação)
Adicionei -  selectedTrack: number; no topo do construtor.

Assim, voltou a funcionar corretamente.

**Comment by zipusbraid91** [comment]
I have found a solution. Put the selectedTrack before the constructor's declaration just like that

selectedTrack;
constructor (...){
}
