### ISSUE TITLE
Dynamic track loading?

### ISSUE THREAD

**Issue by cisnb125** [arielfaur/ionic-audio#14]
Hello, first of all, a huge thanks for this awesome project.

I currently have an ionic-audio code block embedded in my footer like so.

    <ion-audio-track track="myTrack">
      <ion-audio-controls>
        <a class="button button-icon icon" ion-audio-play></a>
        <ion-spinner icon="ios"></ion-spinner>
      </ion-audio-controls>
    </ion-audio-track>

In my controller, $scope.myTrack is dynamically loaded. Whenever an event fires (ionic slide changed), it triggers the following function:

    $scope.slideChanged = function(index) {
      $scope.slideIndex = index;
      var newAudio = $scope.data[index]
  
      $scope.myTrack = {
        url: newAudio.path,
        artist: newAudio.artist,
        title: newAudio.title
      };
    };

Upon update of the scope variable, when I click the "play" ion-audio-controls button, ionic-audio fails with the following console message:

> Error: undefined is not an object (evaluating 'currentTrack.title')
> play@http://IP:8100/lib/ionic-audio/dist/ion-audio.js:140:69
> http://IP:8100/lib/ionic-audio/dist/ion-audio.js:200:25
> http://IP:8100/lib/ionic/js/ionic.bundle.js:24922:30
> completeOutstandingRequest@http://IP:8100/lib/ionic/js/ionic.bundle.js:13604:15
> http://IP:8100/lib/ionic/js/ionic.bundle.js:13984:33

Is this functionality not available currently? If not, do you have plans to add such feature? Or can I please get a pointer as to what I should do to implement it?

Thank you so much.

**Comment by arielfaur** [comment]
You're right. This functionality is not yet implemented. We would need to add a ```$scope.$watch``` to the ```ion-audio-track``` directive and update the ```MediaManager```  dynamically with the new track information. I'm quite busy these past weeks but I will see if I can look into it sometime this week.

**Comment by cisnb125** [comment]
Thank you!

**Comment by jonbongato** [comment]
Hi @arielfaur, I recently have come across this same need and am wondering if you've had a chance to add this functionality?

**Comment by arielfaur** [comment]
Not yet. But I'll do my best to do that in the next week or so.
