### ISSUE TITLE
Local audio

### ISSUE THREAD

**Issue by miniportal** [arielfaur/ionic-audio#143]
I'm trying to play local audio, but nothing happend.
Can you show me an example?

**Comment by zipusbraid91** [comment]
Just replace the src in the track's list by the src of file
Example:

this.myTracks = [
  	{
      src: '../../assets/song1.mp3',
      title: 'Estrellitas y Duendes',
      artist: 'Juan Luis Guerra',
      art: '../assets/img/book1.jpg',
      preload: 'metadata'
    }]

**Comment by Eaderibigbe** [comment]
I like to implement something similar but it is working on android not on iPhone. Anyone ablr to get this to work?

**Comment by zipusbraid91** [comment]
I've only worked in Android just like you, I have not tried it on iPhone. I
give you assurance that Android works.

**Comment by arielfaur** [comment]
#168 
https://github.com/apache/cordova-plugin-file#file-system-layouts
