### ISSUE TITLE
Warnings when building with --prod 

### ISSUE THREAD

**Issue by bockoblur** [arielfaur/ionic-audio#145]
When building with `ionic cordova run android --prod ` I am getting these warnings:

    Warning: Can't resolve all parameters for WebAudioTrack in D:/ionicprojects/strmapp/node_modules/ionic-audio/dist/ionic-audio-web-track.d.ts: (?, ?). This will become an error in Angular v5.x

    Warning: Can't resolve all parameters for CordovaAudioTrack in D:/ionicprojects/strmapp/node_modules/ionic-audio/dist/ionic-audio-cordova-track.d.ts: (?). This will become an error in Angular v5.x

App works, but I just wanted to make an issue here, just in case you are unaware of this..
Great job with this lib!

**Comment by bockoblur** [comment]
**Update:** app built with ` --prod` flag **does not wok** after all - it just hangs at the startup. Without ` --prod` works, and no warnings are displayed during build.

**Comment by arielfaur** [comment]
@bockoblur Can you tell me what versions you are working? Mine compiles with `--prod` without any errors (only those warnings I need to fix)

**Comment by bockoblur** [comment]
Here's the info:

```
> ionic info

cli packages: (D:\ionicprojects\mmpi\node_modules)
    @ionic/cli-plugin-cordova       : 1.6.1
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0
global packages:
    Cordova CLI : 7.0.1
local packages:
    @ionic/app-scripts : 2.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.0
System:
    Android SDK Tools : 26.0.2
    Node              : v6.11.1
    OS                : Windows 10
    npm               : 3.10.10
```

Maybe I was not clear: I am not getting any errors either (just two warnings), but app does not work at all when built with `--prod` flag.

Thanks.

**Comment by arielfaur** [comment]
@bockoblur I just created a build with `--prod`  and run it in the browser with no issues. I am using the sample ionic project here : https://github.com/arielfaur/ionic-audio-demo
In fact that live demo is built with `--prod` , you can inspect it in the console. Do you see any errors logged to the console? Maybe your other modules are complaining?

**Comment by bockoblur** [comment]
When building web project I have no issues.

problem is when building/running **for Android**, as I said in original post:

    ionic cordova run android --prod

Device is then stuck after splash screen (or before splash, I can't remember now and I am not near my dev machine).

**Comment by arielfaur** [comment]
You should try opening the Chrome console on your machine to see what errors are logged. It is hard to tell what's going on otherwise.

**Comment by bockoblur** [comment]
As I recall, no errors were logged when connected as remote debugger.
 I will try it again in a couple of hours when I get to dev machine, and I will get back to you asap.

**Comment by bockoblur** [comment]
Now, it seems that we've entered the TwilightZone™.
App now works on both of my test devices.

Sorry for false alarm.

That leaves only the warnings…

Thank you for responsiveness and good will.

**Comment by bockoblur** [comment]
Thank you. Please don't forget to deal with those warnings.
