### ISSUE TITLE
Test On Android 4.1.2 fails. The track Does not play.

### ISSUE THREAD

**Issue by promactkaran** [arielfaur/ionic-audio#15]
Is there any work around? I have serach n number of ways. But audio does not play on android 4.1.2

**Comment by arielfaur** [comment]
I actually have a Samsung S2 with Android 4.1.2 and it works without any problems. Have you installed the Media plugin?

**Comment by promactkaran** [comment]
Its very strange, Its working now. The problem is with the webView I think. After 2 days of struggling I found out something. Actually I was using css `position: absolute` and `top: 30%` to the audio-player. Strangely running on simulator and devices the click (play button) was not clicking (it was on screen , visible and all but not actually clicking) 

Solution: I had to remove the CSS position absolute and top, and the touch events were working fine then.
