### ISSUE TITLE
Native Audio

### ISSUE THREAD

**Issue by valderind4** [arielfaur/ionic-audio#151]
I would like to know how to implement native audio on Ionic 3. 

I have installed the native audio using:

$ ionic cordova plugin add cordova-plugin-nativeaudio
$ npm install --save @ionic-native/native-audio

But the audio just plays on the app and I can not control on the notification on Android or Media bar on IOS.

Could anyone help me, please?

**Comment by arielfaur** [comment]
The plugin cordova-plugin-nativeaudio is not related to this module. You should post the question on their forum.

**Comment by valderind4** [comment]
Hello @arielfaur I just submitted this issue here because I read on this module doc that It was possible to run native audio, but I added the native audio module and nothing happened. 

Is it possible using your module and run the audio in background mode and control the execution using notification controls (pause, play etc)?

I really want to use this module but I need these features in my app. Can you help me, please?

**Comment by arielfaur** [comment]
If you add cordova-media-plugin then you can have audio in background mode but I am not sure about notification controls. I guess it works on iOS by default but I am not completely sure. Maybe someone else has tried this before?
