### ISSUE TITLE
View status updates on Android 7 in Ionic-Modal

### ISSUE THREAD

**Issue by wetti75** [arielfaur/ionic-audio#154]
The views do not get an update if the player is displayed in an ionic-modal. This is only the case with Android 7. When the device is turned all views get the current state but no updates.

For example, the Play button stays on the status icon-md-play when the audio is started. When the device is turned it gets the status icon-md-pause.

With android 6 and 8 and ios everything works fine.

I use ionic CLI 3.8.1 and ionic-audio ^3.2.0

my Component is:

    <ion-row>
      <ion-col>
        <ion-list>
          <audio-track #audio *ngFor="let track of myTracks" [track]="track" (onFinish)="onTrackFinished($event)">
            <ion-item>  
              <ion-thumbnail item-left>
                <img src="assets/img/Audio.svg"/>
                <audio-track-play dark [audioTrack]="audio"><ion-spinner></ion-spinner></audio-track-play>  
              </ion-thumbnail>
              <div item-content style="width:100%">
                <p><strong>{{audio.title}}</strong></p>
                <audio-track-progress-bar dark duration progress [audioTrack]="audio"></audio-track-progress-bar>
              </div>
            </ion-item>    
          </audio-track>
        </ion-list>
      </ion-col>
    </ion-row>

**Comment by arielfaur** [comment]
@wetti75 That's weird. I mean that it fails only on Android 7, but not on 6 or 8. There isn't much I can do about it I guess.
