### ISSUE TITLE
IONIC 3: Stop another audio when a new one start playing using modal

### ISSUE THREAD

**Issue by satyagvns** [arielfaur/ionic-audio#157]
I am working music player app. I have listed all my tracks in a home page. When I click on any song. The Modal should open and start the music. Problem is both songs are playing at the same time.

Plugin used: ionic-audio [choose for progress bar and basic functionality]

Debug Analysis: When I close and open Modal I am not able to find this.currentTrack value. It is showing 'Undefined'

Can anyone help me to resolve this issue?

**Comment by musmanzpak** [comment]
do you resolve this problem then please share the solution with me also?

**Comment by satyagvns** [comment]
@musmanzpak 

I just followed HTML5 audio APIs and written my own code to resolve most of HTML Player issues.
I am not sure, whether I am right or wrong. But I achieved my target.
