### ISSUE TITLE
Playing multiple tracks simultaneously

### ISSUE THREAD

**Issue by chalosalvador** [arielfaur/ionic-audio#158]
Hello, I'm developing an app that needs to play multiple tracks simultaneously. It works perfectly fine when I test it in the browser (all the tracks play in sync with each other), but when I deploy it to a phone the tracks don't sync well and there is a delay so the music doesn't sound nice.

Does anybody know a way to allow the tracks start playing exactly at the same time so they always sound in sync with each other?

Here is the repo where I have a demo of what I'm implementing:
https://github.com/chalosalvador/demoIonicAudio

The demo has a button that plays the same track 3 times and another button that plays the track only once so you can see the difference. When you play the track three times simultaneously you can hear that it is not starting exactly at the same time so it sounds weird.

I hope someone can help me.

**Comment by arielfaur** [comment]
For that I would use a different plugin or the Web Audio API, especially if you need to sync tracks.

http://www.schillmania.com/projects/soundmanager2/
