### ISSUE TITLE
 previous track in one page is not stopping, when new track is played from another page(infinite scroll)

### ISSUE THREAD

**Issue by ahijahboaz** [arielfaur/ionic-audio#161]
I have implemented infinite scroll loading all the audio files from the remote server. Per page am loading 5 files. If am playing audio files within a page, the pausing of the previous track happens when playing new track. But if a track is played in one page, and if i try to play a new track from another page, the existing track is not getting paused. Please help. Thank you so much in advance.

**Comment by arielfaur** [comment]
#179

**Comment by infotheme** [comment]
//Add this 
 ionViewWillUnload() {
	this._audioProvider.pause(this.selectedTrack);
  }
//right before
  ionViewDidLoad() {

100% working tips. Welcome in advance

  Also please subscribe my blog : [How to Make OTP System In PHP](https://www.infotheme.in/blog/2016/08/make-otp-system-in-php.html)

**Comment by infotheme** [comment]
u can also do

 ionViewWillUnload() {
	this._audioProvider.stop(this.selectedTrack);
  }
