### ISSUE TITLE
Not Working with Bluetooth Audio

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [arielfaur/ionic-audio#163]
Hey, I can not get this to work properly with Bluetooth audio. It starts the song and says it is playing and has loaded but no progress happens in the song. The only way I can get audio in Ionic View is to play the song through the speaker at first and then connect Bluetooth headphones. It'll work until the next song tries to load.

**Comment by arielfaur** [comment]
This plugin is simply a wrapper. It's out of scope.
