### ISSUE TITLE
Not Playing Saved Audio file on iPhone

### ISSUE THREAD

**Issue by Eaderibigbe** [arielfaur/ionic-audio#164]
Hello,
I am implementing version 3.2.0 and streaming from a url is ok but playing a saved audio file is not working on iPhone but working on android. I tried both cordova and web audio. Below is error I got as I will appreciate your help.

Audio error => track file:///var/mobile/Containers/Data/Application/4286D16E-3EE4-41B4-93FC-9FE4749552C1/Documents/M950.mp3 [object Object]
2017-10-31 09:15:07.588967+0100 RCCG LAP[1443:642590] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (NaN) in JSON write'

Kindly note that the file is on the device

2017-10-31 09:15:06.552694+0100 RCCG LAP[1443:642590] Loading track file:///var/mobile/Containers/Data/Application/4286D16E-3EE4-41B4-93FC-9FE4749552C1/Documents/M950.mp3
2017-10-31 09:15:06.555248+0100 RCCG LAP[1443:643619] Will attempt to use file resource 'file:///var/mobile/Containers/Data/Application/4286D16E-3EE4-41B4-93FC-9FE4749552C1/Documents/M950.mp3'
2017-10-31 09:15:06.555487+0100 RCCG LAP[1443:643619] Unknown resource 'file:///var/mobile/Containers/Data/Application/4286D16E-3EE4-41B4-93FC-9FE4749552C1/Documents/M950.mp3'
2017-10-31 09:15:06.572677+0100 RCCG LAP[1443:642590] Audio error => track file:///var/mobile/Containers/Data/Application/4286D16E-3EE4-41B4-93FC-9FE4749552C1/Documents/M950.mp3 [object Object]
2017-10-31 09:15:07.588967+0100 RCCG LAP[1443:642590] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (NaN) in JSON write'
*** First throw call stack:
(0x18426fd38 0x183784528 0x18426fc80 0x184cef4c0 0x184cee044 0x184cf0688 0x18420942c 0x184cefda8 0x184ceddf4 0x184ceee44 0x104a78884 0x104a83444 0x104a782c8 0x104a6a494 0x104a82200 0x104953dd8 0x104953c3c 0x10495581c 0x193553250 0x1934e7e00 0x1934e9fe0 0x1932d5b10 0x1934b2820 0x1932960ec 0x193298ae0 0x18b49cd10 0x18b49cfd0 0x184218358 0x1842182d8 0x184217b60 0x184215738 0x1841362d8 0x185fc7f84 0x18d6e3880 0x104922cfc 0x183c5a56c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by mubasshir** [comment]
did you get any solution for this?

**Comment by Eaderibigbe** [comment]
Not at all

**Comment by mubasshir** [comment]
what did you do then?

**Comment by Eaderibigbe** [comment]
For IOS I removed option of saving audio file to be played later but for
iOS you can save file locally and play latter

**Comment by mubasshir** [comment]
I'm bit confused with your reply.

**Comment by hphirke** [comment]
@adedapo 
Could you explain what you mean by:

> for iOS you can save file locally and play latter

I am also looking for an app which can download and play audio locally but getting an error

**Comment by Eaderibigbe** [comment]
Hello
Samething I wish to implement. On Android I was able to download the audio
and play locally. On iOS, I was also able to download but couldn't play
locally reason I opened the issue.

I am looking at removing the option to download and play locally from the
iOS version.

Hope it helps

**Comment by borodiliz** [comment]
Same problem here. It was a headache, but I finally found the solution:

* Ensure you are using cordova-media-plugin https://ionicframework.com/docs/native/media/
* Ensure `ionic-audio`uses `CordovaMediaProvider` on `app.module.ts`:

```app.module.ts
import {IonicAudioModule, WebAudioProvider, CordovaMediaProvider, defaultAudioProviderFactory} from 'ionic-audio';
...
export function myCustomAudioProviderFactory() {
   //Just for testing, force to use CordovaMediaProvider
   return new CordovaMediaProvider();
}
....
   //Just for testing, move to defaultAudioProviderFactory after validating 
IonicAudioModule.forRoot(myCustomAudioProviderFactory),
```
* Pass `src` path to `ionic-audio` without the initial _file://_  :
``` yourcode.ts
        //Problems on IOS devices but not in Android devices. Use decodeURIComponent to access file without problems.
        this.singleTrack = {
            src: decodeURIComponent(this.src).replace(/^file:\/\//, '');
            artist: '',
            title: ''
        };
```

Probably also solves #92 

@arielfaur Should ionic-audio work with local files using WebAudioProvider on IOS?

**Comment by mubasshir** [comment]
@borodiliz  I will definitely check this, thanks

**Comment by arielfaur** [comment]
#168 

Have you checked the file path? There are lots of issues related to the same topic. Please try not to create duplicate issues.  In most cases this is due to a wrong path. Take a look at the File plugin which has constants that map to the appropriate path on Android and iOS.
