### ISSUE TITLE
Ionic 3.9.2 and Angular5 support

### ISSUE THREAD

**Issue by napcat** [arielfaur/ionic-audio#167]
I was getting a warning during build time saying that the current latest version will be not compatible with angular 5.

Yesterday the Ionic team updated theirs framework to version 3.9.2 and added support to Angular 5.

What kind of incompatibility does this plugin have with Angular 5?

Is it secure to update or will we need an update?

**Comment by mubasshir** [comment]
+1

**Comment by betatools** [comment]
I am using this with Angular 5 and Ionic 3.9.2 and it works just fine. When I build I now get the warning

> Can't resolve all parameters for WebAudioTrack in.....
> This will become an error in Angular v6.x

I am using it on iOS and Android

**Comment by bockoblur** [comment]
@betatools did you also try --prod build? Works ok? I reported this (issue #145 , now closed) some time ago, and I'm not sure should I update to Angular 5...

**Comment by betatools** [comment]
@bockoblur Yes I use it in production and have build with --prod

**Comment by bockoblur** [comment]
Thank you. Guess it's ok then. At least until Angular 6.x is released. :)

**Comment by arielfaur** [comment]
This one has been fixed with the latest update. Thanks!
