### ISSUE TITLE
iOS Bug: Not able to play again

### ISSUE THREAD

**Issue by mubasshir** [arielfaur/ionic-audio#171]
Hi,
I'm using this in Chat module where I've ChatPage, which loads ChatBubbleComponent. Inside ChatBubble, I've used your track code. 

In iOS, its track plays once perfectly but when I try to play again, it gives me error code 4(media plugin used).

Even if I play another track, they won't work and give me same error.

**Comment by CrispyFriedPig** [comment]
Hi mubasshir,
Maybe I meet the same issue like yours.
Hope below infomation can help you. 
Did your audio src uses server url ?
I geess  there is something wrong when the audio plugin run on ios with server url.
I tried to download the audio first, then give the local url to the audio src.
At last, it works! 
Oh, I forget to tell you that you can download audio from server by the file transfer plugin, please see the below url:
https://ionicframework.com/docs/native/file-transfer/

**Comment by mubasshir** [comment]
Hi,
I'm using local files still doesn't work.

**Comment by CrispyFriedPig** [comment]
Hi mubasshir,

Sorry, I don't know your details. Make sure your code and related permission is right.
Just try it with a simple demo reference to the official document first.

**Comment by arielfaur** [comment]
If you have a public link to your project maybe I can look at it. It is hard to tell otherwise.

**Comment by mubasshir** [comment]
I understand. I will try to make a public repo in days

As of now, I've to drop this and using Streaming Media Plugin
