### ISSUE TITLE
[ask] how to stop if user go to other menu

### ISSUE THREAD

**Issue by edwinnsan** [arielfaur/ionic-audio#172]
hello..
i want ask, how to stop audio if user go to other menu / user not in list page of audio how to stop it? Because now its always play on background. Thanks

**Comment by 95deepan** [comment]
Any updates @arielfaur  && @edwinnsan  ?

**Comment by edwinnsan** [comment]
Oh this problem already solved, thank you for reminding me @95deepan

**Comment by 95deepan** [comment]
Can you please elaborate how did you solve ? @edwinnsan

**Comment by edwinnsan** [comment]
you can do it like this


`  ionViewCanLeave() {
    this.audioProvider.pause(this.selectedTrack);
}`


ionviewcanleave is function when we press back button...
its backbutton on ionic apps, not in hardware back button..

**Comment by 95deepan** [comment]
Didn't work for me.. because `this.selectedTrack` whose value is '0'. When I passed this value to `this.audioProvider.pause()` function, it is not working.

**Comment by edwinnsan** [comment]
why u passed the value '0'?

this.selectedTrack is like default value from this module, dont replace it, just write the code same with me.

**Comment by arielfaur** [comment]
Hi all,

I haven't had time to look into all issues lately. And especially this one feature. The plugin might need a small refactor for this to work. I hope I can find the time to look into this sometime soon...

**Comment by arielfaur** [comment]
#140
