### ISSUE TITLE
Ionic-Audio_Master and Detail Page

### ISSUE THREAD

**Issue by lion32033** [arielfaur/ionic-audio#173]
Hey,

Please I need your Help. 
I work with your Data:
https://github.com/arielfaur/ionic-audio

and I tried to create master- and detail page but I don't solve this. I don’t have much experience with Ionic. 

Please see attached file PDF (Screenshots) to understand what I mean:
[Ionic_Audio_Master & Detail Page.pdf](https://github.com/arielfaur/ionic-audio/files/1534158/Ionic_Audio_Master.Detail.Page.pdf)

I would like to have only this:
**Master Page:** 
List- Song names

**Detail page**
Play Button, Pause Button and the Progress bar 
(we can play and stop the clicked song).

Thank you for your Help.

**Comment by arielfaur** [comment]
I am sorry I can't assist you with Ionic development. Try to find some online tutorials for master-detail in Ionic.

**Comment by lion32033** [comment]
I will pay you. Please I nead this. How much you want to make this for me?
Thank you
