### ISSUE TITLE
onTrackFinished always looping and not stop.

### ISSUE THREAD

**Issue by abitul** [arielfaur/ionic-audio#175]
onTrackFinished always looping and not stop when play mp3 with long time

![screen shot 2017-12-12 at 15 05 45](https://user-images.githubusercontent.com/33111326/33873615-49af2ae8-df4e-11e7-9862-bd1d39ee3706.png)

please help me..

thanks,

**Comment by ludobit** [comment]
I've same issue with version ^3.2.0
