### ISSUE TITLE
No mention of any preload options other than "metadata" or "none"

### ISSUE THREAD

**Issue by alecrem** [arielfaur/ionic-audio#178]
I have been trying to find a way to preload whole files (small and local filesystem) and I realized it's never explained if one can choose anything other than "none" or "metadata" when defining tracks.

```ts
      preload: 'metadata' // tell the plugin to preload metadata such as duration for this track,  set to 'none' to turn off
```

I would be really happy if there's a way to preload the whole track, but anyway I'd be happy to contribute more specific (while short) wording for the explanation about preloading. Once I fully understand it, of course! Could anybody share some info on this?

**Comment by arielfaur** [comment]
@alecrem The plugin is a simple wrapper for HTML audio and uses the same parameters as input.

https://www.w3schools.com/tags/att_audio_preload.asp

**Comment by alecrem** [comment]
Thank you! I didn't know that. Now I understand why that's not specified on your plugin's docs. It was just me being clueless about HTML audio.
