### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by puterleat** [arielfaur/ionic-audio#18]
Would it be possible to broadcast events when the player status changes, for example to enable other elements to update to indicate a track is playing, or for analytics code?

**Comment by arielfaur** [comment]
Sure. You mean a simple ```$rootscope.$broadcast``` with the new status code? Right now this is being done only to notify the progress bar but that can be easily added.

**Comment by tbergeron** [comment]
Any news from @puterleat ? Inactive issue? Can we close this?
