### ISSUE TITLE
Loading time abnormally long on Android

### ISSUE THREAD

**Issue by manufao** [arielfaur/ionic-audio#181]
Hi,

I am developing an app on ionic 3 to listen live radio but I have an issue with some url on android device (all works fine on ios). Loading time is abnormally long.

Do you know why some data take more time to load on android than ios ?

My configuration :
cli packages: 
    ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0
global packages:
    cordova (Cordova CLI) : 7.1.0
local packages:
    ionic/app-scripts : 1.3.12
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.5.0
System:
    Android SDK Tools : 26.1.1
    Node              : v8.3.0
    npm               : 5.5.1
    OS                : Linux 4.9

Thanks in advance

**Comment by arielfaur** [comment]
I really don't know. In most cases it depends on the streaming server or the audio format. You could try both html audio and the cordova media plugin to see if it improves loading times.
