### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by adeyo92** [arielfaur/ionic-audio#19]
Hi!

I was wondering if this plugin has been tested on iOS yet?

**Comment by arielfaur** [comment]
Hi! Yes it works on iOS ☺️

**Comment by adeyo92** [comment]
Hi, 
I implemented this last night in a streaming app I was working on, It worked fine on my android but on my iOS device it freezes once I hit the play button. I'm not sure why.

**Comment by arielfaur** [comment]
What iOS version are you on? iOS will freeze the UI while the track is loading by default, but then the track should start playing. At least that is the behavior I have seen and what others have reported. Can you see anything in the console?

**Comment by adeyo92** [comment]
Hi, I am using iOS version 7.1.2. When I ran the ionic serve command and opened the console I saw "ionic-audio: missing Cordova Media Plugin. Have you installed the plugin?
Run 'ionic plugin add org.apache.cordova.media'" 

But I have already installed the cordova media plugin

**Comment by arielfaur** [comment]
This will not work with ```ionic serve```. You need to test on your device.
There's an error in the documentation. To make sure you have the latest Media plugin remove it and add it again with:
```ionic plugin add cordova-plugin-media```

**Comment by adeyo92** [comment]
Hi,
I removed the media plugin and reinstalled it, I ran it on my iOS device, but it still freezes again. It still plays fine on the android

**Comment by arielfaur** [comment]
Is it an iPhone 4? I've never tested on iOS 7.1.2. Only on iOS 8.4.1 and 9.
You should be able to do remote debugging if you have your iPhone plugged to your dev machine and open Safari as explained here:
http://phonegap-tips.com/articles/debugging-ios-phonegap-apps-with-safaris-web-inspector.html
 
Then you can open your device's console window while you're running your app. Let me know if you see any messages there.

**Comment by leonardosalles** [comment]
You checked if sound starts play after a minute? If you use this on iOS the app will freeze until all the audio files is downloade.

**Comment by adeyo92** [comment]
I was able to get it working about a month ago. I think it was because I was trying to access an m4a file not an mp3. Thanks for the

**Comment by leonardosalles** [comment]
You're welcome.

**Comment by nuruddinbadawi** [comment]
who I can make play Audio When Screen Is Locked in IOS?

**Comment by arielfaur** [comment]
You need to enable background audio in xCode

**Comment by nuruddinbadawi** [comment]
in IOS when start playing its take long time to starting play and spinner is frozen 
how to fix this and thanks?

**Comment by arielfaur** [comment]
There is no fix for that. That's how the Cordova Media works.

**Comment by badawiZad** [comment]
hi ..
I have a problem with IOS when to play any Audio the app is freeze 10 sec or 15 after that is start play 
why ?

**Comment by nuruddinbadawi** [comment]
![screen shot 2015-12-23 at 13 48 30](https://cloud.githubusercontent.com/assets/5736522/11978139/e3f5de98-a991-11e5-935b-d9a3b82e7402.png)

I have problem in ios when play audio app is freezing 
please any solution if anyone know how fix this ?

**Comment by adeyo92** [comment]
I think that's just how it works for iOS. Since the cordova media plugin does not support streaming, it is going to freeze until the audio file is completely downloaded. I would suggest using maybe Web Audio API instead 
example: https://www.airpair.com/ionic-framework/posts/using-web-audio-api-for-precision-audio-in-ionic

**Comment by nuruddinbadawi** [comment]
this article's very complicated .

**Comment by nuruddinbadawi** [comment]
Is there a way to solve the freezing problem temporarily?
For example, show loading or something else.

**Comment by nuruddinbadawi** [comment]
who I can allow stop audio in background mode and I enable background mode in xCode and work good 
but the problem is I can't pause audio outside application .

**Comment by arielfaur** [comment]
You can use ```MediaManager.stop()``` as explained here: http://arielfaur.github.io/ionic-audio/#MediaManager

**Comment by bazimov** [comment]
I think cordova media plugin 2.2 newest version has fixed the issue.
