### ISSUE TITLE
Using seekTo to resume track playing on next launch

### ISSUE THREAD

**Issue by rdai** [arielfaur/ionic-audio#192]
Hi, 

One quick question please. When an user pauses the audio in the middle of playing, I am storing that in a variable, so on the next launch, if that variable exists, I'd like to advance the track to that position so the user can resume playing from last time. 

I have this ALMOST working. The problem is that it seems the seekTo function only works once the track has started playing so when I do seekTo when just loading the play list, no error and no seekTo really happened. I even tried to set `this._audioProvider.tracks[id]['_progress']` from my storage variable, then in playSelectedTrack function, right before playing to see if `this._audioProvider.tracks[id]['_progress'] > 0` but even this doesn't work

`        this._audioProvider.play(id);
        this._audioProvider.tracks[id].seekTo(this._audioProvider.tracks[id]['_progress']);`

because the play event has a "loading track" part which finishes and then seekTo try to run before the track actually start playing and it fails again. play does seem to be a promise that I can chain onto. I tried to play with the variables in the audioTrack object but nothing seems to do the trick.

Ideally, say we are 30 seconds in, I'd like to see the progress bar with the position set to 30 seconds, and the play resume from that position. I've tried for many hours to get this to work but maybe I am missing something obvious.  Thanks!

**Comment by rdai** [comment]
Quick update, I was able to resume at the location by going straight down to `ionic-audio-web-track` (onTimeUpdate) and `ionic-audio-cordova-track` startTimer functions. Having set the _progress parameter during load, I check `if (this._progress > this.audio.currentTime){                
               this.seekTo(this._progress);
            }` for example. It is probably not a great idea to modify this plugin directly and if this inspires anyone, please test heavily as I need to. I still trying to figure out if it is possible to have the progress bar displaying on load when there have been progress before, so the user know they will be "resuming" when they click, instead having the audio jump unannounced.

**Comment by rdai** [comment]
Ok, figure out how to set the progress bar loading too. I saved the position/progress of previous play. When I load the tracks again, I set
`    this._audioProvider.tracks[findIdx]['_duration'] = val._duration;
this._audioProvider.tracks[findIdx]['_completed'] = Math.round(val._progress / val._duration * 100) / 100;` 

`findIdx` is the id of the track in question, you have to use your own variable for that, 
`val` is the value I retrieved from storage. 

Maybe this will help someone in the future.

**Comment by leoohee** [comment]
cool. I m looking for this for so long time.

thx

**Comment by ghonche** [comment]
Thanks for the solution. but I can't figure out how to get the position of music every second?
