### ISSUE TITLE
Enhancement: HTML5 Audio fallback (for ionic serve/view for example)

### ISSUE THREAD

**Issue by eminos** [arielfaur/ionic-audio#2]
The title says it all :)

**Comment by arielfaur** [comment]
I thought about this, but it would clutter the module and increase the codebase all of that for the sake of testing on the dev machine. I guess it is more important to keep the codebase to a minimum and avoid any issues related to performance... just an idea. What do you think?

**Comment by eminos** [comment]
I don't know how much extra code that would be, probably not that much (?). But in that case the best solution would be to have an "plugin module for fallback", maybe with a "fallback" directive, to extend the normal functionality with that fallback (if that's possible at all?) during development.

**Comment by arielfaur** [comment]
I'm just scared this module is already more than 400 lines of code, we'll need minification :)
But I will look into that.

**Comment by leonardosalles** [comment]
@arielfaur I think you can separete the module of HTML5 audio, and it can be removed with a cordova hook when we make the build, so you will only need to include the module and the javascript of HTML5 audio, like 'ionicAudio.HTML5Mock' and remove it when it is not on the dev. I can work on this feature and submit a pull request, sounds good for you?

**Comment by arielfaur** [comment]
It was on my roadmap too. But go ahead and submit a pull request!

**Comment by leonardosalles** [comment]
Sure, I will implement the way that I mention

**Comment by Narayon** [comment]
The HTML5 Audio implementation is really small. Take a look at this: 	
goo.gl/SwFVga
Besides that, why should we use the Cordova Media plugin instead of the HTML5 Audio element or even the Web Audio API? Is it more performant? More options?

**Comment by arielfaur** [comment]
@Narayon  It's on the TODO list!

**Comment by cypherq** [comment]
@arielfaur can I help you with this? You have any concept of "how to implement this"? Just want to create fasade/proxy service which will decide what strategy use for playing audio?

**Comment by phishy** [comment]
@Narayon  Because on iOS the HTML5 Audio element doesn't work in the background without the cordova media plugin.

@arielfaur The description of this repo is misleading. It says it uses HTML audio as fallback. I can't see any mention it, unless I'm missing it?

**Comment by arielfaur** [comment]
@phishy The HTML audio fallback is for v2! Sorry if the description is misleading. The v2 is on a separate branch though.

**Comment by tbergeron** [comment]
Inactive issue? Can we close this?
This is already working in v2 and v3 if I'm not mistaken.

**Comment by arielfaur** [comment]
@tbergeron Yes, let's close it.
