### ISSUE TITLE
Bower main property

### ISSUE THREAD

**Issue by Neophy7e** [arielfaur/ionic-audio#21]
Hi,

Can you please add "main" : "dist/ion-audio.js" in bower.json ?

It would enable wiredep to automatically add ionic-audio dependencies to the index.html.

Thanks

**Comment by zooofeex** [comment]
Hi,

meanwhile you can override your bower's configs
https://github.com/taptapship/wiredep#bower-overrides

**Comment by Neophy7e** [comment]
That's what I did, I just find it cleaner to not overrides them in case of you add other dependencies in the future or change the filename

**Comment by arielfaur** [comment]
I can certainly add that. I will do it as soon as I find some free time. Feel free to send a pull request if you prefer!

**Comment by arielfaur** [comment]
Done!
