### ISSUE TITLE
How i can get current playing value from ionic-audio ?

### ISSUE THREAD

**Issue by nuruddinbadawi** [arielfaur/ionic-audio#25]
i need to change style for progress bar and use other progress but i need to pass current timer when playing 
how ? and thanks .

**Comment by arielfaur** [comment]
To change the style of the progress bar I would recommend using ```ng-class```: 
```
<div class="item" ng-class="{ 'item-positive': $first, 'item-energized': $last}">
            <ion-audio-progress-bar display-time></ion-audio-progress-bar>
</div>
```

Check this example: http://codepen.io/anon/pen/pjGXGX

**Comment by blueror815** [comment]
Hi Arielfaur.
I used ionic audio to play audio
But progress bar is not working.
My code is like below
`<ion-audio-track track="track" ng-show="podcast.url != undefined">
                    <div class="card audio-card">
                        <div class="item" style=" padding-right: 0px !important; padding-left:10px !important">
                            <ion-audio-controls>
                                <button class="button button-small button-assertive icon-left" ion-audio-play text-play="Play" text-pause="Pause"></button>
                                <ion-audio-progress-bar track="track" display-time></ion-audio-progress-bar>
                            </ion-audio-controls>
                        </div>
                    </div>
                </ion-audio-track>`
Do you have any idea?
