### ISSUE TITLE
Audio not play until file downloaded to device, screen no response during download

### ISSUE THREAD

**Issue by frannnnk** [arielfaur/ionic-audio#27]
Thanks for the amazing plugin, I have a problem with it however. I have lots of audio files in the server which is pretty large, say from 10MB to 120MB, when testing the player in simulator I found that it seems the player will only play the audio until the whole audio file has been downloaded to the device, while during downloading process the device is frozen in the screen and cannot do anything, no percentage indicator or progress bar can be seen. 

May i know if this is the true? i.e. player need to download the whole file before playing. If true, any way to stream the audio when downloading and showing the download percentage? 

iOS 9.1 iPhone6

**Comment by frannnnk** [comment]
I think it is pretty confirmed that the audio won't play until it is fully downloaded. in this way is there a way to display a download status, or first download the file using filedownload api and then play it as a local file, which provides a better user experience.

**Comment by arielfaur** [comment]
Yes, this has been discussed in another thread here. The Cordova media plugin does not support streaming, it will download the whole file before starting playback. In your case I would use HTML5 audio which supports progressive download, or implement my own player using the Web Audio API. I am currently working on a new version of ionic-audio which will support HTML5 audio too, so that developers can configure the plugin to use wither Cordova Media or HTML5 audio depending on their needs. In the meantime, you may look at the options I have mentioned.

**Comment by leonardosalles** [comment]
@frannnnk I have the same problem and solved it by download the file in background using a plugin [Cordova Download Background](https://github.com/sgrebnov/cordova-plugin-background-download) and when download is complete I used the file from fileSystem, this work perfectly for me but remember to set all files that you download to not send it to icloud, I created a gist with the code that I used, you can check it [here](https://gist.github.com/leonardosalles/e18984407389e29edcd4), if you see I created a folder with the same approach

**Comment by frannnnk** [comment]
Thanks @leonardosalles and @arielfaur , I made some mod to arielfaur's API and added the ability to download the file first (using cordova file transfer) with a friendly progress bar, and once the file is downloaded it will start playing. By the way @leonardosalles you mentioned not to send the downloaded file to iCloud, beside the iCloud storage concerns is there any other concerns for this? Such as if Apple will reject the app if i store the downloaded audio file to iCloud? 

Thanks again both.

**Comment by leonardosalles** [comment]
@frannnnk I'm not sure buddy, but if you add the file to backup on iCloud I think you need to store the file at the right iCloud directory, you can check [this link](http://makina-corpus.com/blog/metier/2014/the-right-location-for-your-cordova-app-files) for more information to how not sync files, but I think Apple will reject your app if you dont put BackupWebStorage to false at you config.xml
