### ISSUE TITLE
Play Audio in background

### ISSUE THREAD

**Issue by BrettKoenig** [arielfaur/ionic-audio#29]
Hey, 
I was wondering if there is a way to have the audio play when the app is minimized or the screen is locked.

I found for the cordova media plugin you can pass a parameter to the play function like below:
var iOSPlayOptions = {
                numberOfLoops: 1,
                playAudioWhenScreenIsLocked: true
            }
            currentMedia.play(iOSPlayOptions);

But this doesn't seem to be working with this plugin. Any thoughts?

Thanks, this plugin is awesome!

**Comment by arielfaur** [comment]
Hi @BrettKoenig ! You need to enable background audio in xCode. If I remember correctly the switch is located in Target -> Capabilities -> Background Modes. There you simply need to enable background audio.

**Comment by BrettKoenig** [comment]
Thanks for the quick response @arielfaur !

**Comment by rodolfobubb** [comment]
didn't work for me
