### ISSUE TITLE
$scope.track.play is not a function

### ISSUE THREAD

**Issue by nuruddinbadawi** [arielfaur/ionic-audio#31]
hi ! , after update 'Uncaught TypeError: $scope.track.play is not a function' .

**Comment by arielfaur** [comment]
What is your use case? Can you show me your code?

**Comment by nuruddinbadawi** [comment]
in my controller :
```
        Api.getFeedSingle($stateParams.feedId)
            .then(function(result) {
                $scope.item = result;
                if(result.sound != 'NO'){
                    $scope.hasSound = true;
                    $scope.tracks  =
                        {
                            url:result.sound,
                            title:result.title
                        };

                    }
```

in html :
```
   <ion-audio-track track="tracks">
                <div class="list card ">
                    <div class="item item-avatar">
                        <img src="img/audio_wave.png">
                    </div>
                    <div class="item item-divider">
                        <ion-audio-progress-bar display-time></ion-audio-progress-bar>
                    </div>
                    <div class="item tabs tabs-secondary tabs-icon-left">
                        <ion-audio-controls>
                            <a class="button button-icon icon" ion-audio-play></a>
                            <ion-spinner icon="ios" style="position: relative; top: 8px; left: 4px"></ion-spinner>
                        </ion-audio-controls>
                    </div>
                </div>

            </ion-audio-track>
```

after load page show me " $scope.track.play is not a function " just this .

and thanks :+1:

**Comment by arielfaur** [comment]
I see you are dynamically assigning ```$scope.track```. That use case was not supported.
I am currently working on a version that makes tracks observable so that should work for your case.
Can you try the version from this branch? https://github.com/arielfaur/ionic-audio/tree/feature-track-observable
There is only one breaking change in this version: you need to add the track property to the progress bar too. Just like you do with ```ion-audio-track```:
````
<ion-audio-progress-bar track="track" display-time></ion-audio-progress-bar>
```` 
Let me know if it works for you.

**Comment by nuruddinbadawi** [comment]
yes with this branch sound work will
good work :+1: 
and tell me when finish new version.
------------------------
Question :
i need to ask if you support backward and forward sound ?

-------------------------
sorry for inconvenience and thank you .

**Comment by arielfaur** [comment]
You mean something like a playlist? Not yet. But it's on the TODO list!

**Comment by nuruddinbadawi** [comment]
i mean forward is same media not next media in playlist

**Comment by arielfaur** [comment]
This is already in there. The progress bar has a slider that lets you move forward within a track.

**Comment by nuruddinbadawi** [comment]
And About Download Locally
New eagerly await :)
Thank you for good work .

**Comment by nuruddinbadawi** [comment]
hello pleas i need some help
how i can manage this :
- when press back button i need to continue media playing why stopping ?
- also i need to show media controller for pause or stop audio in status bar

and thank you

**Comment by leonardosalles** [comment]
@nuruddinbadawi you talk about statusbar at the top on ios? or the control center at the bottom of device?

**Comment by arielfaur** [comment]
@nuruddinbadawi  To download audio locally you need to use $cordovaFileTransfer, that is out of the scope of this module.
If you are on iOS you need to enable background audio in xCode. Also make sure your $scope isn't destroyed when you switch views, otherwise playback will stop.
For the status bar I have no idea. Maybe you need a separate service for that.

**Comment by nuruddinbadawi** [comment]
the $scope is not destroyed because when to navigate between state is not stop playing just when I press back button 
who fixed ?

**Comment by arielfaur** [comment]
It's hard to tell what's going on without seeing code. Maybe you can create a codepen with the use case you are describing.

**Comment by nuruddinbadawi** [comment]
after debugging 
when press back button execute  MediaManager.destroy(); in line 273
```
  $scope.$on('$destroy', function() {
            MediaManager.destroy();
        });
```

What is the reason that doing Destroy ?

**Comment by arielfaur** [comment]
That is to avoid memory leaks, it simply releases the media resources when the scope is destroyed. But the problem seems to be that your scope is being destroyed. Have you disabled view caching?

**Comment by nuruddinbadawi** [comment]
No Caching is Available

**Comment by arielfaur** [comment]
You can comment that line in the source code if you find it inconvenient.

**Comment by nuruddinbadawi** [comment]
i tried enable forwardCache " $ionicConfigProvider.views.forwardCache(true) " 
and working good :dancer: 
this is good idea ?

**Comment by arielfaur** [comment]
Yes! I just read about it, seems to solve exactly your problem.

**Comment by Luwangnoob** [comment]
Hi,
How do i add thumbnail inside ion-audio-progress-bar??
please help---

**Comment by satish22** [comment]
@arielfaur - When i try to assign dynamic/single progress bar for my audio files i get below error
please help here....

'ion-audio-controls' is not a known element:
1. If 'ion-audio-controls' is an Angular component, then verify that it is part of this module.
2. If 'ion-audio-controls' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (">{{dynamicTrack.title}}</h2>
                    <p>{{dynamicTrack.artist}}</p>
                    [ERROR ->]<ion-audio-controls>
                        <a class="button button-icon icon" ion-audio-play></a>
 "): ng:///Module/Page1Page.html@8:20



HTML -
<ion-view view-title="Dynamic tracks">
    <ion-content>      
        <ion-audio-track track="dynamicTrack" toggle-playback="togglePlayback">
            <div class="card">
                <div class="item">
                    <h2>{{dynamicTrack.title}}</h2>
                    <p>{{dynamicTrack.artist}}</p>
                    <ion-audio-controls>
                        <a class="button button-icon icon" ion-audio-play></a>
                        <ion-spinner icon="ios" style="position: relative; top: 8px; left: 4px"></ion-spinner>
                    </ion-audio-controls>
                </div>
                <div class="item item-divider">
                    <ion-audio-progress-bar track="dynamicTrack" display-time></ion-audio-progress-bar>
                </div>
            </div>
        </ion-audio-track>
    </ion-content>
</ion-view>


Thank you

**Comment by arielfaur** [comment]
hi @satish22 
that version for ionic 1 is no longer maintained, sorry. No time for that!
