### ISSUE TITLE
How to make it work with ng-repeat based on JSON feed 

### ISSUE THREAD

**Issue by kyoshiro2708** [arielfaur/ionic-audio#33]
Hi,

I cannot make it work with the below code : 

Controller (gets the JSON feed from my URL as an Array and put it in rootScope.musiques) : 

      $http.get('myURL').then(function (resp) {
               $rootScope.musiques = resp.data.posts;
      }

In HTML : 
Using ng-repeat to get the track info one by one from the array.
The thumbnail & title is showing correctly, but when clicking on the play button, it doesn't happen anything. I already tried your other branch "observable", but with no luck. 

Any idea ? 

              <div class="list list-inset" ng-repeat= "track in musiques"  on-refresh="doRefreshMusique()">   

                <ion-audio-track track="track">

                  <div class="item item-thumbnail-left">

                    <img ng-src="{{track.thumbnail_images.full.url}}" class="feed-image">

                    <p>{{track.title}}</p>
                    <ion-audio-controls>
                      <a class="button button-icon icon" ion-audio-play></a>
                      <ion-spinner icon="ios"></ion-spinner>
                    </ion-audio-controls>
                  </div>
                  <div class="item">
                    <ion-audio-progress-bar track="track" display-time></ion-audio-progress-bar>
                  </div>
                  </ion-audio-track>
                </div>
Thank you for your help.

**Comment by arielfaur** [comment]
Why are you using ```$rootScope``` to bind data to the view? Can't you use ```$scope.musiques``` to bind data to your view?

**Comment by kyoshiro2708** [comment]
Indeed, I could use $scope instead of $rootscope, but this doesn't solve the issue.

I think I found it, but have no idea how to fix it.

My Json provide this info for the url ==> url: "http://MyURL.be/2015/12/14/Michael-Jackson-2/", which is the link of the article that contains the MP3 and not the link to the MP3 itself. 

Is there a way to change the attribute URL in ly code to be any attribute I would like to use in my Json ? As I need to create a custom field that will contain the MP3 url.

**Comment by arielfaur** [comment]
I am not sure I understand the problem. What do you mean with the article that contains the mp3?

**Comment by kyoshiro2708** [comment]
Basically, I have a news website in which, each page contains news information. 
From the website, I can generate a JSON per page like : 

     "posts": [
        {
            "id": 13914,
            "type": "post",
            "title": "tax-litigation-at-your-door-test",
            "url": "http://myURL.be/2015/12/10/tax-litigation-at-your-door-test/",
           "custom_fields": {
                "mp3_url": [
                    "http://myURL.be/2015/12/10/tax-litigation-at-your-door-test.mp3"
                ]
        },
        {
            "id": 13823,
            "type": "post",
            "title": "entertainment-industry-acquisitions2",
            "url": "http://myURL.be/2015/11/25/entertainment-industry-acquisitions2/",
            "custom_fields": {
                 "mp3_url": [
                     "http://myURL.be/2015/12/10/entertainment-industry-acquisitions2.mp3"
                ]
        ]

So I would like your code to read my custom field "mp3_url" instead of the field url (which in my case contains the link to the news, not to the mp3 itself).

Hope this is clear enough.

**Comment by arielfaur** [comment]
I see the problem now. What you need to do is apply a mapping function to your JSON array to create a new array with the properties the ionic-audio module expects. Something like this:

```
// assuming resp.data.posts is an array
$http.get('myURL').then(function (resp) {
           $scope.musiques = resp.data.posts.map(function(post) {
                return {
                  title: post.title,
                  url: post.custom_fields.mp3_url,
                  ....
                }
           });
}
```

And here's the documentation for ```map``` : 
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by kyoshiro2708** [comment]
Thank you very much !! That's exactly what I needed.
I have been able to generate my list of tracks based on the JSON.

Last question : When pressing the play icon, the song starts, but the spinner doesn't move nor it shows the duration of the song on the right of the spinner's line.

I have this code : 

          <div class="item item-divider">
            <ion-audio-progress-bar display-time></ion-audio-progress-bar>
          </div>

What am I missing ?

**Comment by arielfaur** [comment]
Are you using the code from the observable branch? If so you need to add the ```track``` parameter to the progress bar.

**Comment by kyoshiro2708** [comment]
Thanks a lot for your help, everything works fine now.

You can close the topic.
