### ISSUE TITLE
how to add two ion-audio-track with sync?

### ISSUE THREAD

**Issue by nuruddinbadawi** [arielfaur/ionic-audio#34]
hi .. 
I want to add tow ion-audio-track one in the page contetnt and the other in top controller 
this mean parent audio controll for manage inside other pages
I tried to add ion-audio-track in tow place and make track in rootScope for sharing the same data
but the problem is progress bar not working in two place
there are other options for doing it like this?

**Comment by arielfaur** [comment]
In order to bind track data to the view, the data needs to assigned to your view's  $scope (not the global $rootScope). You could use Angular event system to communicate between views.
