### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'play' on Android

### ISSUE THREAD

**Issue by remib** [arielfaur/ionic-audio#35]
I had the plugin working previously with an older version of cordova but since updating to the latest, I get this error while running on an Android device:
    
    Uncaught TypeError: Object #<Object> has no method 'play' 

My usage case follows the same as the example on the ionic audio website. When I tap the play button I see the loading spinner but get the above error in console.

The media plugin is installed and the code has not changed since I had it working. The only thing I changed was I updated cordova which meant I had to create a new project but I copied everything from the www folder and readded the plugins. 

I had a nightmare getting videos to play on Android in the same App so I had to use the file and file-transfer plugins to access the video files. Could this be a similar problem?

**Comment by arielfaur** [comment]
Can you post some code? Are you loading your tracks dynamically by any chance?
