### ISSUE TITLE
iOS spinner stops while file downloads

### ISSUE THREAD

**Issue by OJcode14** [arielfaur/ionic-audio#36]
Appears the spinner stops while the file is downloading on iOS before playing, giving the impression of a freeze or a crash...

I'm using the feature-track-observable branch as I'm using signed URL's and setting the track URL dynamically. 

Any ideas why the spinner does that?

**Comment by arielfaur** [comment]
Yes this has been discussed quite a few times. It is the expected behavior in iOS because the Media plugin needs to download the entire media before playback is possible. See #11
