### ISSUE TITLE
Spinner is not getting disappear and pause button not converted to play button after finishing music play in android.    

### ISSUE THREAD

**Issue by mrbankim** [arielfaur/ionic-audio#37]
Hi Arielfaur,

Issue with android platform.

**Comment by mrbankim** [comment]
Hi,

Now i am able to run it on android too. The problem was for android "cordova-plugin-media" was not installed, so now play button is working but after complete the track pause button is not changing to play button again and spinner is still moving continuously after finish the track.

Thanks.

**Comment by mrbankim** [comment]
Hi, 

May be the issue is due to bellow console output. But I am not sure. I have update android to 5.0.0. Still the same issue.

["Plugin doesn't support this project's cordova-android version. cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev"]

Bankims-MacBook-Pro:myAudio bankimdebnath$ sudo ionic plugin add cordova-plugin-media
Updated the hooks directory to have execute permissions
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev
Skipping 'cordova-plugin-media' for android
Plugin "cordova-plugin-media" already installed on ios.
Saving plugin to package.json file

Can you please look into this?

**Comment by arielfaur** [comment]
@mrbankim sorry it took me long to reply. I am really busy these weeks. This type of issue has been reported a few times. In general, this is related to some missing/corrupt files in your project. I see you have permission issues with your project. I don't think you should run ```ionic``` with ```sudo```. Maybe some OSX expert can comment on this but I would start with a fresh project, install Media plugin (without sudo) and check if it works.

**Comment by mrbankim** [comment]
But the same is working fine for iPhone.

**Comment by arielfaur** [comment]
Can you open your device console while the app is running and see if there are any errors logged?

**Comment by mrbankim** [comment]
No, there is no any error logs. :(

**Comment by arielfaur** [comment]
Try removing the platform and adding it again. Has worked in the past to fix some inconsistencies.

**Comment by mrbankim** [comment]
several times I have created fresh projects but all the times it is same.

**Comment by arielfaur** [comment]
I am rereading your logs. It seems you need to update your cordova version. Run ```cordova -version```
On my computer I get: 5.1.1

**Comment by mrbankim** [comment]
For me:  cordova -version
5.4.1
Bankims-MacBook-Pro:myAudio bankimdebnath$

**Comment by mrbankim** [comment]
See the log .. I have removed and ad it again. not getting this err log.

Installing "cordova-plugin-media" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev
Skipping 'cordova-plugin-media' for android

**Comment by arielfaur** [comment]
What happens if you run ```cordova platform update android```

**Comment by mrbankim** [comment]
No, nothing happen.. after update i ran this.. see the log below. But if i run "cordova platform update android@5.0.0"  then it i am not getting below error log.


ionic plugin add cordova-plugin-media
Fetching plugin "cordova-plugin-media" via npm
Installing "cordova-plugin-media" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 4.1.1, failed version requirement: >=5.0.0-dev
Skipping 'cordova-plugin-media' for android
Plugin "cordova-plugin-media" already installed on ios.
Saving plugin to package.json file
Bankims-MacBook-Pro:myAudio bankimdebnath$

**Comment by arielfaur** [comment]
How are you using the module? Maybe a code sample from your controller to see if there's anything there.

**Comment by mrbankim** [comment]
Is it due to something latest version of Android or Cordova?

**Comment by arielfaur** [comment]
What do you mean?

**Comment by mrbankim** [comment]
I just downloaded the code sample from your repository and ran it after adding "cordova-plugin-media" and "bower install ionic-audio".

**Comment by mrbankim** [comment]
Thanks for your time. Please have a look into this once you will get time. :) Thanks again..

**Comment by mrbankim** [comment]
Hi, 

This is really a genuine issue. I have deployed the same in windows system and ran there also same issue (Spinner is not getting disappear and pause button not converted to play button after finishing music play in android). As you told me that may be problem with sudo i used in mac but for windows also I am getting the same issue. Please have a look into this, other wise it is use less. no one can use this.

**Comment by joelelangovan1985** [comment]
+1

**Comment by joelelangovan1985** [comment]
Installed Perfectly on another app, which i created 15 days ago, but now its not working in my new project.  Here is my controller 
`app.controller("ExampleController", function ($scope) {

  $scope.track = {
    url: 'http://k003.kiwi6.com/hotlink/cay8j82ed1/Introduction_to_Romans_-_Tamil_message.mp3',
    //url: 'https://googledrive.com/host/0B_0gV-62NNMNd0d6NXY2UjU0Wkk/1.Five_points_for_fruitfulness.mp3',
    artist: 'Somebody',
    title: 'Song name',
    art: 'img/album_art.jpg'
  }

});
`
and here is my index file : 

`<ion-content ng-controller="ExampleController">
    <ion-audio-track track="track">
      <div class="list list-inset">
        <div class="item item-thumbnail-left">
          <img src="{{track.art}}">
          <h2>{{track.title}}</h2>
          <p>{{track.artist}}</p>
          <ion-audio-controls>
            <a class="button button-icon icon" ion-audio-play></a>
            <ion-spinner icon="ios"></ion-spinner>
          </ion-audio-controls>
        </div>
        <div class="item">
          <ion-audio-progress-bar display-time></ion-audio-progress-bar>
        </div>
      </div>
    </ion-audio-track>
  </ion-content>`

When you click on play, song starts playing but the spinner keeps on spinning and the pause button no longer works, 
here is my console error which i get : 
![capture](https://cloud.githubusercontent.com/assets/5588760/12729800/78ead6c6-c94e-11e5-8051-ee087c5ee54b.PNG)

Thank you very much, i am working on a project which needs this plugin very much, would be great if you could fix this problem.

**Comment by arielfaur** [comment]
@joelelangovan1985 do you see any errors in the javascript (web) console?

**Comment by arielfaur** [comment]
@mrbankim I cannot reproduce the problem on any of my devices so there is nothing I can do. It seems you're also the only one having this issue. Maybe you can send me your APK file, or you can upload the project somewhere.

**Comment by mrbankim** [comment]
Hi, Thanks for your reply.

I think @joelelangovan1985  also facing same problem. Anyway I am sending you the apk file. Please have a look on this. Please give your email id so i can send it to you.

**Comment by arielfaur** [comment]
Send it to ariel.faur@gmail.com

Make sure it is compiled in debug mode.

**Comment by mrbankim** [comment]
I send it to you. Please have a look and let me know.

**Comment by joelelangovan1985** [comment]
@arielfaur I don't get any errors in my web console. I am sending you the project folder, so you can have a look, its just your example-audio folder with platform added and apk built. I am sending you the apk file.

**Comment by arielfaur** [comment]
I think I have found the cause. It seems that both of you are using a newer version of ```cordova-plugin-media``` that doesn't seem to be compatible with the current ```cordova-android``` version.
To fix this do:
```
cordova plugin rm cordova-plugin-media

cordova plugin add cordova-plugin-media@1.0.1
```

Then build your project as usual. Let me know if this fixes the issue.

**Comment by joelelangovan1985** [comment]
@arielfaur You are awesome, Works perfectly .

**Comment by joelelangovan1985** [comment]
Thank you so much !

**Comment by joelelangovan1985** [comment]
is it possible to play when app is in background , like native audio player, Showing progress of the song in the status bar, is it possible in cordova ? Would be great to get your advice.

**Comment by arielfaur** [comment]
It does play in the background if you switch apps. Showing a notification in the status bar is another thing, I haven't looked into this. But it's out of the scope of this plugin at the moment.

**Comment by mrbankim** [comment]
Hi @arielfaur

Thank you.. It is working.. :)

**Comment by mrbankim** [comment]
Grt work.. :)
