### ISSUE TITLE
Changing the track URL

### ISSUE THREAD

**Issue by sherifdarwish** [arielfaur/ionic-audio#38]
Hi @arielfaur 

Thanks for your efforts in creating this nice module, i was working on it and i had a requirement to change the track url based on some conditions then play sound from the new URL, i was building this with cordova so i am using the cdvfile://localhost/ file system

I was able to achieve this by adding a new listener to track url as below in ionAudioTrackCtrl

let me if this sound correct and can be a nice enhancement for this module

       $scope.$watch('track.url', function () {
            if (!MediaManager) return;

            // Stop playing the current track
            MediaManager.stop();

            // Update elements & add as new track 
            init();

            // attach play funtion
            $scope.track.play = function () {

                MediaManager.play($scope.track.id);

                // notify global progress bar if detached from track
                if (!controller.hasOwnProgressBar) notifyProgressBar();

                return $scope.track.id;
            };
        });

**Comment by arielfaur** [comment]
Hi @sherifdarwish That is already available in the latest version of this module.

**Comment by sherifdarwish** [comment]
This is  great and thanks for adding this, i was not aware of this new version but i will start using it 

Regards,
Sherif
