### ISSUE TITLE
Couldn't run example-audio on iOs emulator without a path modification

### ISSUE THREAD

**Issue by est-seb** [arielfaur/ionic-audio#39]
In www/js/controllers.js we can see 
`var urlprefix = '/android_asset/www/audio/';`
When I ran "ionic emulate ios" the audio files couldn't be found.
I could make it work using 
`var urlprefix = 'audio/';`

I don't see how to make it to make it work in both cases yet.

**Comment by arielfaur** [comment]
Yes, the local folders in Android and iOS are different. If you are playing local audio you need to set the path accordingly using ```ionic.Platform``` to detect the platform

http://ionicframework.com/docs/api/utility/ionic.Platform/
