### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by ascendedmasta** [arielfaur/ionic-audio#4]
This is a great module! 

Any plans for playlist support? Being able to move forward and back through a playlist while stopping, and possibly releasing audio resources would be very helpful.

**Comment by arielfaur** [comment]
I am refactoring parts of the module and am planning to include playlist support. I am just worried about performance when adding multiple tracks... I should run some tests. If you have any ideas let me know.

**Comment by ascendedmasta** [comment]
Something that mimics your current format would be nice...

    <ionic-audio-playlist playist="tracks" class="list list-inset">
        <ionic-audio-track ng-repeat="track in tracks" track="track">
        ...
        </ionic-audio-track>
    </ionic-audio-playlist>

The playlist part would be only for handling controls of the playlist:
Current Selected track and it's current state (playing, paused, or stopped)
Setting current track via skip fwd/back, or by selecting a specific track in the list
Releasing the current playlist and track when the user switches views, or playlist

**Comment by arielfaur** [comment]
So the playlist should contain the playback controls in this case. I would welcome some help if you have time :)

**Comment by ascendedmasta** [comment]
I'll have a look at the ionic-audio.js when I get a free sec. I may be able to help a bit. :)

**Comment by llaine** [comment]
+1

**Comment by edjeezy** [comment]
+1

**Comment by tbergeron** [comment]
I'm trying to help out on this (for Ionic 3 at the moment) here are related issues:
https://github.com/arielfaur/ionic-audio/issues/122
https://github.com/arielfaur/ionic-audio/issues/114
https://github.com/arielfaur/ionic-audio/issues/88

IMO we should close this issue for inactivity and use the most recent ones.
