### ISSUE TITLE
ReferenceError: Can't find variable: nan

### ISSUE THREAD

**Issue by herve1976** [arielfaur/ionic-audio#40]
I am trying to test the example app but I am getting the following error:

exeption nativeEvalAndFetch : ReferenceError: Can't find variable: nan

and the music is not playing.

H

**Comment by arielfaur** [comment]
So weird. First time I ever hear of that error. Anything else on the console?

**Comment by herve1976** [comment]
here is the logs that keep repeated:

2016-03-09 12:08:10.796 example-audio[1397:602293] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> Invalid number value (NaN) in JSON write
2016-03-09 12:08:10.803 example-audio[1397:602293] exeption nativeEvalAndFetch : ReferenceError: Can't find variable: nan
22    890794   log      exeption nativeEvalAndFetch : ReferenceError: Can't find variable: nan

**Comment by arielfaur** [comment]
Is that Android or iOS?

**Comment by herve1976** [comment]
iOS

**Comment by arielfaur** [comment]
I can't help you with this because I am on Android. But maybe you can open Safari Developer console to see the javascript console of your device and see if there are any errors there.

**Comment by Taewa** [comment]
@herve1976 Maybe you can just change the path? 
https://github.com/arielfaur/ionic-audio/issues/39

**Comment by Taewa** [comment]
@arielfaur I think this error message is shown when iOS device can't find a file. In my case I am using streaming and when the streaming is not working, I get a same error message.
Can I get some event when this message shows up via js?
Once this error occurs then I can't play even any other audio files that are playable.

**Comment by arielfaur** [comment]
I will try to find time to look into it!

**Comment by nuruddinbadawi** [comment]
I have the same Issue , I play audio after download in local and pass local Url to track.URL, but appear like this error 

> ReferenceError: Can't find variable: nan

**Comment by nncl** [comment]
+1

**Comment by cinder92** [comment]
+1 

i have same issue, but i'm not using this plugin, i'm using cordova-media and cordova media returns this error, is very weird because in native code from iOS they call a javascript function (Media.onStatus), audio (streaming in my case) is playing ok, but i get same error like you 'can't find variable nan' maybe a type of error in variable types?

**Comment by cinder92** [comment]
guys! you should update cordova-media plugin to latest one! they fix my problem!

**Comment by arielfaur** [comment]
Hi @cinder92 
Can you confirm that updating the Cordova media plugin fixes this issue? Also, could you please state the media plugin version you are using?
Thanks!

**Comment by solilius** [comment]
had that problem and apparently you cant have any while spaces in your audio path
but i opened the project after a week and the problem is back..

**Comment by yoojene** [comment]
Hi All, also having this issue on device - no spaces in URL.

@cinder92 if you can confirm which version of the media plugin worked for you would be appreciated

I am currently on:

 "cordova-plugin-media": "3.0.1".

**Comment by jh3141** [comment]
I've also seen this problem with latest version of cordova-plugin-media (actually https://github.com/jh3141/cordova-plugin-media.git, which is a fork that's tracking the upstream master, but it only has android-related changes so shouldn't affect this). I'm using the plugin directly, not with the framework provided by this project, so I'd say it's definitely a cordova/iOS platform/media plugin bug, and not a bug here.
