### ISSUE TITLE
Missing Cordova Media plugin (Ionic v1.7.14)

### ISSUE THREAD

**Issue by suchac** [arielfaur/ionic-audio#41]
Hello, I've done all your installation steps and also succesfully installed Cordova Media plugin, I can see it in `package.json` file and I also get `cordova-plugin-media 2.1.0 "Media"` by running command `ionic plugin list` so I suppose I have this plugin installed.
But no audio player shows on my page and I am getting this error in the console:
```
ionic-audio: missing Cordova Media plugin. Have you installed the plugin? 
Run 'ionic plugin add cordova-plugin-media'

ionic.bundle.js:21162 TypeError: Cannot read property 'stop' of null
    at Object.fn (ion-audio.js:320)
    at Scope.$digest (ionic.bundle.js:24515)
    at Scope.$apply (ionic.bundle.js:24783)
    at done (ionic.bundle.js:19196)
    at completeRequest (ionic.bundle.js:19368)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:19309)
```

Do you have any idea why is that so? Have I installed wrong version of Cordova Media plugin or is there something that I forgot to install?

**Comment by arielfaur** [comment]
Try this:
```
cordova plugin rm cordova-plugin-media

cordova plugin add cordova-plugin-media@1.0.1
```

**Comment by suchac** [comment]
Didn't help.
Anyway, I found out that the issue occurs only in develpoment in my web browser (`ionic serve`). When I run it on my phone, everything works ok.

**Comment by arielfaur** [comment]
That's correct. It is also mentioned in the documentation that cordova plugins won't work in the browser, only in the emulator or a real device.

**Comment by suchac** [comment]
Ok, thanks a lot for your help :+1:

**Comment by kpennell** [comment]
@arielfaur If you're tired of browser questions, you might put it in huge bold writing.  Just a suggestion.

Is there any easy way we can test functionality and whatnot without having to constantly run ionic build ios and wait a while for it to build?

**Comment by arielfaur** [comment]
@kpennell I might take your advice :)

Unfortunately it seems to be no other way. I put up those demos on the site so that it is easy to define the UI for the media player. If you want to test audio playback you will have to build the project. I am actually planning to rewrite the module so that we can use Web Audio API as a fallback. That would work both in the browser and on the device.

**Comment by Taewa** [comment]
Just for a little tip for someone who try example-audio in iOS device.

Change from
`var urlprefix = '/android_asset/www/audio/'` 
to
`var urlprefix = '/audio/'`

then you will see the audio is working properly on iOS device.

**Comment by pothagoni** [comment]
Getting an error while install ionic-audio package.

 bower install ionic-audio
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower cached        git://github.com/driftyco/ionic-bower.git#1.3.1
bower validate      1.3.1 against git://github.com/driftyco/ionic-bower.git#1.3.1
bower cached        https://github.com/arielfaur/ionic-audio.git#1.3.1
bower validate      1.3.1 against https://github.com/arielfaur/ionic-audio.git#*
bower ENOTFOUND     Package Favicon JS=favicon not found


Installed using ionic command, installed successfully.
ionic plugin add cordova-plugin-media

but didn't see the ionic-audio-master package.
Manually download the package into lib directory and add the script tag.

I don't see any error but audio player not showing.
Can you please help.
