### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by kpennell** [arielfaur/ionic-audio#43]
Guessing you're aware that the demos don't play?

**Comment by kpennell** [comment]
sending out an SOS (forgive the bad joke)

**Comment by arielfaur** [comment]
You mean in the browser or the device?

**Comment by kpennell** [comment]
your demo page tracks don't play

**Comment by arielfaur** [comment]
Yes, and they are not supposed to play. The plugin only works in the device or emulator. it's in the documentation :)

**Comment by kpennell** [comment]
Snap, really?  What is the purpose of that?

**Comment by arielfaur** [comment]
Cordova plugins will only work once installed on your device or the emulator because they're native components.
