### ISSUE TITLE
ionic-audio: missing Cordova Media plugin. 

### ISSUE THREAD

**Issue by kpennell** [arielfaur/ionic-audio#44]
Hey Arielfur,
Really trying to do things right.  Getting the `ionic-audio: missing Cordova Media plugin.`  I've run the `ionic plugin add cordova-plugin-media` and I see cordova-plugin-media right there in my plugins folder.  Any idea why I'm getting that error?

I ran `ionic plugin rm cordova-plugin-media` and `ionic plugin add cordova-plugin-media`.

**Comment by arielfaur** [comment]
I assume this is happening on your device, right? Any other messages in the javascript console?
It looks as though either Cordova or the plugin hasn't installed correctly.
What Cordova version are you running? You can find out with:
```
cordova -v

cordova platform list
```

**Comment by kpennell** [comment]
MacBook-Pro:sampCoachSide Test$ cordova -v
6.0.0
MacBook-Pro:sampCoachSide Test$ cordova platform list
Installed platforms: android 4.1.1, ios 3.9.2
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, osx, webos

**Comment by kpennell** [comment]
Is odd, still haven't been able to shake that error. It's not detecting something.

**Comment by arielfaur** [comment]
Do you see that error on both Android and iOS?

**Comment by OwenMelbz** [comment]
I'm getting the same issue, has there been any movement on resolving this?

**Comment by arielfaur** [comment]
have you tried uninstalling the Media plugin and adding it back again?

**Comment by OwenMelbz** [comment]
@arielfaur I'd love to say no, and that it worked. However I've tried several times through different methods including ionic cli and the cordova cli, going to try it on a different machine later, but feel like maybe something has updated cordova end that has broken something. Even started looking at the v2 - however the beta ionic cli is erroring all over the shop and the documentation no longer matches what is actually produced by the tool
