### ISSUE TITLE
Weird file issue

### ISSUE THREAD

**Issue by Ardathalion** [arielfaur/ionic-audio#47]
Hi,
I got an .mp3 file that I am trying to play in an ionic app. I've tried your very nice plugin with several other files. Everything seemed to work - but not with the file I got. Here's what I've done so far:

- try online/offline
- validate the mp3 file
- converted the .mp3 to .wav and .aiff 
- used different settings on .mp3 conversion
- change sample rate
- check file permissions
- check my code, but since your test audio is working I'm not too worried about this

Do you have any hint for me on what else could cause it not playing. In Xcode as I test the app it would say "now playing ..." but no sound whatsoever. In android there still seems to be another issue since the loading indicator just runs wild with nothing happening. (but I am not the one testing the android app, so I cannot give more info on that atm)

**Comment by arielfaur** [comment]
I really don't know and I cannot guess what the issue is. It probably has to do with the file format and Cordova Media plugin.
