### ISSUE TITLE
Its not working in Android

### ISSUE THREAD

**Issue by matheuztavarez** [arielfaur/ionic-audio#48]
I can't Skip a song using the slide, nor the loading symbol disappears... And after the song is played it won't stop anymore. Any solutions?

**Comment by arielfaur** [comment]
It's hard to know...Are there any errors in the javascript console?

**Comment by matheuztavarez** [comment]
Cant really test in browser cuz it won't play media.. So just tested on devices.. on iPhone works perfectly but not on android... Just used the main code, so it should work as its working in one platform... :P

**Comment by arielfaur** [comment]
On Android you can enable remote debugging so you can see the device's console on your Chrome browser on your dev machine.

**Comment by matheuztavarez** [comment]
oh yea! Shit! Forgot that ! Gonna post the results asap!

**Comment by matheuztavarez** [comment]
![screenshot 2016-04-21 09 49 15](https://cloud.githubusercontent.com/assets/8632748/14709300/51764210-07a6-11e6-8206-fe586d5eecb6.png)
Thats what appears with the inspector, if i play all songs I can't stop them nor skip in the slider, and the loading symbol don't stop... No errors found...

**Comment by matheuztavarez** [comment]
Did anyone got to work with android?..

**Comment by arielfaur** [comment]
It's hard to know, I cannot guess what is wrong. My first guess is that you are playing remote files, keep in mind that Cordova Media does not support streaming. If the files are big it will take long until the plugin downloads the whole media before playing.

**Comment by m4s4kr** [comment]
Hello, I certify that the application for Andorid nefugnuje. I made an application of your tutorial here: http://arielfaur.github.io/ionic-audio and the audio begins to play, pause does not work. The log does not display any errors.

**Comment by m4s4kr** [comment]
Hello, I acknowledge that the application does not work on Andorid. I made an application of your tutorial here: http://arielfaur.github.io/ionic-audio and the audio begins to play, pause does not work. The log does not display any errors.

**Comment by arielfaur** [comment]
What ionic version are you on?

**Comment by matheuztavarez** [comment]
Yea.... Im in the latest version and im playing files from links, it worked seamlessly in the iPhone, like,really perfect, but a lot of bugs with android :(

**Comment by arielfaur** [comment]
Do you mean the latest ionic 1.3?

**Comment by matheuztavarez** [comment]
Yea

**Comment by arielfaur** [comment]
Ok, i found the problem! It is a bug in Cordova Media. Please do the following:
````
cordova plugin rm cordova-plugin-media
cordova plugin add cordova-plugin-media@2.2.0
````

**Comment by matheuztavarez** [comment]
Worked as a charm!! Thanks a lot @arielfaur !!! But any ideas how to make the sliding div, with the info of the song and shit always visible? I mean, like a footer? Tried to put inside a ion-footer-bar  but didn't work :/

**Comment by arielfaur** [comment]
I guess it should work inside a footer

**Comment by nicolasguzca** [comment]
Adding
`cordova plugin add cordova-plugin-media@2.2.0`
also worked perfectly for me. It will be awesome if you could put it on the documentation :)
