### ISSUE TITLE
Progress bar will only 'seek to' while the track is playing

### ISSUE THREAD

**Issue by ascendedmasta** [arielfaur/ionic-audio#5]
Progress bar only moves while the track is playing, and not when the current track is stopped.

**Comment by arielfaur** [comment]
I've just released a new version (v1.2.3). Can you give it a try? Seek-to seems to work fine now , at least on Android.

**Comment by ascendedmasta** [comment]
Works perfect. Tested on iOS 6, 6Plus, and Mini2

Sorry for the late reply. I've been in training all week. I'm out tomorrow.

**Comment by arielfaur** [comment]
Thank you @ascendedmasta! Closing this issue.
