### ISSUE TITLE
Safari shows blank page

### ISSUE THREAD

**Issue by yuyinitos** [arielfaur/ionic-audio#50]
Safari shows a blank page when providers are specified as below. The `<ion-app></ion-app>` is empty. If no providers are set `providers: []` then Safari shows the app correctly. (`<ion-app>...</ion-app>` has content) Emulation in iOS has the same issue.
In either case Safari reports the error `ReferenceError: Can't find variable: AudioContext` at ionic-web-track.ts:25:91. 
In Chrome all above works fine.

> import {App, Platform} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {TabsPage} from './pages/tabs/tabs';
import {AudioProvider, WebAudioProvider} from 'ionic-audio/dist/ionic-audio';
>
> // https://angular.io/docs/ts/latest/api/core/Type-interface.html
import {Type, provide} from 'angular2/core';
>
@App({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  config: {}, // http://ionicframework.com/docs/v2/api/config/Config/
  providers: [provide(AudioProvider, { useFactory: AudioProvider.factory })] // or use [WebAudioProvider] to force HTML5 Audio  
})
export class MyApp {
  rootPage: any = TabsPage;
>
  constructor(platform: Platform) {
    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }
}

It maybe due to this typescript error when building:
`TypeScript error: /Users/Eugene/Code/mindfood/node_modules/ionic-audio/dist/ionic-audio-providers.ts(30,19): Error TS2339: Property 'cordova' does not exist on type 'Window'.`

**Comment by arielfaur** [comment]
@yuyinitos thanks for reporting this bug. I fixed it already. The new module version is 2.0.4 and is already available on npm.
Let me know if it works!

**Comment by yuyinitos** [comment]
v2.0.4 did the trick. Thanks!
