### ISSUE TITLE
MediaManager not defined 

### ISSUE THREAD

**Issue by nuruddinbadawi** [arielfaur/ionic-audio#51]
when load page has media files show this error : 

> Error: null is not an object (evaluating 'MediaManager.stop')

when click play shows this error :

> TypeError: null is not an object (evaluating 'MediaManager.play')

Debug ..

<img width="553" alt="screen shot 2016-05-20 at 17 12 59" src="https://cloud.githubusercontent.com/assets/5736522/15430866/e07e5c84-1eaf-11e6-98ee-a3febada52d1.png">

**Comment by arielfaur** [comment]
Can you tell me what version of the module you are using? And also your Ionic version.

**Comment by nuruddinbadawi** [comment]
ionic info :

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014


bower file :

{
  "name": "rmmapp",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.3.0"
  },
  "dependencies": {
    "lokijs": "^1.3.16",
    "ngCordova": "^0.1.26-alpha",
    "lodash": "^4.12.0",
    "font-awesome": "fontawesome#^4.6.3",
    "ionic-audio": "^1.3.0",
    "angular-moment-hijri": "^0.1.0"
  },
  "resolutions": {
    "angular": "1.4.3"
  }
}

**Comment by arielfaur** [comment]
This is strange I would need to know more about your project. I haven't seen this one before.
Are there any errors in the device console?

**Comment by nuruddinbadawi** [comment]
before add ionic-audio I have an error cause stop the application 

<img width="937" alt="screen shot 2016-05-16 at 21 00 58" src="https://cloud.githubusercontent.com/assets/5736522/15436021/5fe8393c-1ec8-11e6-92fa-1695f6ac8129.png">

the error very strange and I don't know what the reason until now, and I tried to remove the cordova.js file from index.html, after that it's work without cordova file

now I add cordova.js into the index and back the Error 

this cordova error before install ionic-audio,
Is it possible to be the MediaManegar Error because I removed cordova.js  ? and what is the relationship ?

**Comment by arielfaur** [comment]
That seems to be an error related to the platform which is causing the module to fail, because it needs the ```cordova-plugin-media```.
Try removing the platform and adding it back again.

**Comment by nuruddinbadawi** [comment]
still appear the error.

**Comment by arielfaur** [comment]
What version of ```cordova-plugin-media``` do you have?

**Comment by nuruddinbadawi** [comment]
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-crosswalk-webview 1.7.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.1.0 "SocialSharing"
ionic-plugin-keyboard 2.2.0 "Keyboard"

**Comment by arielfaur** [comment]
Ok, try this now:
````
cordova plugin rm cordova-plugin-media
cordova plugin add cordova-plugin-media@2.2.0
````

**Comment by nuruddinbadawi** [comment]
should I keep  cordova.js file in index page ?

**Comment by arielfaur** [comment]
Yes

**Comment by nuruddinbadawi** [comment]
same thing.

**Comment by arielfaur** [comment]
Just to make sure, you are running this on your iOS device right?

**Comment by nuruddinbadawi** [comment]
in ios Emulator

**Comment by arielfaur** [comment]
Can you try your device to see if the error shows up ?

**Comment by nuruddinbadawi** [comment]
Android work will , IOS same Error 

> TypeError: null is not an object (evaluating 'contents.length')

<img width="1097" alt="screen shot 2016-05-20 at 22 51 34" src="https://cloud.githubusercontent.com/assets/5736522/15440315/805dc686-1edd-11e6-9bce-b75182b10599.png">
