### ISSUE TITLE
stop audio when use ion-infinite-scroll

### ISSUE THREAD

**Issue by nuruddinbadawi** [arielfaur/ionic-audio#52]
I using ion-infinite-scroll just I push item in the-the base Audio array but when to load more Item the audio stops and reset to zero.

any solution for this case?

**Comment by arielfaur** [comment]
i don't think I understand what you are trying to do. can you explain in more detail?

**Comment by nuruddinbadawi** [comment]
OK no problem ..
I have list of sound larg list for that I'm using infinte-scroll, but when start play any sound work will but if I scroll and bring new items in this list, but the sound stop when push new item.

I using Angular 1.5, and this list I make it as component.

**Comment by arielfaur** [comment]
Where do you push new items into? Are you dynamically changing the ```tracks``` array that contains the URLs for each audio?

**Comment by nuruddinbadawi** [comment]
yes change the whole array and Tracks is an item in this array.

**Comment by arielfaur** [comment]
if you change the array containing the tracks the bindings will stop working, so this use case is not supported

**Comment by nuruddinbadawi** [comment]
there is any way to get current track and put it in other array ? other meaning who catch item when play click it and move it to other place ?

And Sorry For Disturb

**Comment by arielfaur** [comment]
Have you solved this issue?

**Comment by nuruddinbadawi** [comment]
alas,  it's not solved yet.

**Comment by arielfaur** [comment]
I think you will have to somehow change your workflow and avoid changing the array containing audio tracks. I have never tested a use case like the one you're trying to address.

**Comment by tbergeron** [comment]
Inactive issue? Can we close this?

**Comment by arielfaur** [comment]
I still need to look at this use case, but will focus on v2
