### ISSUE TITLE
'ion-audio.min.js' is not same as ion-audio.js

### ISSUE THREAD

**Issue by Taewa** [arielfaur/ionic-audio#53]
Hello.
First of all, thank you for nice plugin for audio player. It is so useful for my project.

I found out an error when I use `ion-audio.min.js` instead of using `ion-audio.js`

However, if I run `npm install` and `gulp build`, it re-generates `ion-audio.min.js` then `ion-audio.min.js` is working properly.

I found out the difference between original `ion-audio.min.js` and my own re-generated `ion-audio.min.js`.
I attach the screenshots (The left is re-generated by `gulp build`, and the right is original `ion-audio.min.js`)

![screen shot 2016-05-23 at 11 28 11](https://cloud.githubusercontent.com/assets/10694180/15466573/9391cfa0-20da-11e6-8b0d-fb5ace529f5d.png)
<img width="952" alt="screen shot 2016-05-23 at 11 28 29" src="https://cloud.githubusercontent.com/assets/10694180/15466575/95f42d42-20da-11e6-932b-623c7d8a6901.png">

Can anyone fix `ion-audio.min.js` on github?
By doing so I don't have to run `npm install` and `gulp build` in `ionic-audio` directory whenever I checkout my project.

Thank you.

**Comment by arielfaur** [comment]
This is really weird. The ```gulp build``` command runs the default javascript minification task, it should without any problems. At least I haven't heard anyone else complain (or it could be that nobody's using the minified version...).
What errors do you see in the console?

**Comment by tbergeron** [comment]
Inactive issue? Can we close this?
