### ISSUE TITLE
Force play

### ISSUE THREAD

**Issue by llaine** [arielfaur/ionic-audio#54]
Hello,
How can I force the change of the currently played  track?

Here is my view :
```
<ion-audio-track ng-repeat="track in roomCtrl.tracks" track="track">
      <div class="item item-icon-left">
        <ion-audio-controls>
          <a class="button button-icon icon" ion-audio-play></a>
        </ion-audio-controls>
        <h2>{{track.title}}</h2>
      </div>
    </ion-audio-track>
```

And in the controler I want to do something like this :

```
// Reassign directly
$scope.track = tracks[position++];
```

Do I need to force something?

**Comment by arielfaur** [comment]
In theory you could reassign ```$scope.track``` because each ```ion-audio-track``` has a watcher. Whenever any of its properties change the plugin updates itself.

**Comment by llaine** [comment]
Okay I've tried to do it this way and it's not working like this unfortunatly. 
Actually I've done a tiny playlist feature on my project (based on your repo).

But whenever I reassign directly the `$scope.track` it doesn't seems to updates itself. The only way it work is to `$scope.togglePlayback = !$scope.togglePlayback`. 

But it cause the song to play twice and don't toggle off the ion-pause class on the previous track played. 

You can find my [code](https://github.com/llaine/room-guide/blob/master/www/js/controllers.js#L17) where i'm experiencing this issue and [here](https://github.com/llaine/room-guide/blob/master/www/lib/ionic-audio/dist/ion-audio.js#L214)
  the changes I've done on your repo to mimic the playlist feature

**Comment by arielfaur** [comment]
Have you seen the builtin example project ? It does exactly that.

**Comment by llaine** [comment]
Yes I tried to use this as possible to do mine. 

what is togglePlayback doing exactly?

**Comment by arielfaur** [comment]
Everything is explained in the documentation, especially under "NEW in version 1.3.0":
http://arielfaur.github.io/ionic-audio/

After you assign the ```track``` you need to set ```togglePlayback``` to true to start playback or false to stop.

**Comment by llaine** [comment]
I understand all that but dude, togglePlayback set to true doesn't do anything. That's why I opened this thread to try to understand why it doesn't work and maybe I should do something else.

**Comment by arielfaur** [comment]
OK, I have looked at your code. I am not able to follow all of it but at first glance, I think the problem may be that you have placed two different directives on the same element here:
 https://github.com/llaine/room-guide/blob/master/www/templates/room.html#L15

The ``` ng-click='playTrack($index)'``` should be on a separate element I think. That will trigger the dynamic assignment of  ```$scope.dynamicTrack``` like in the example. Also you could place the ```$scope.togglePlayback``` inside ```playTrack``` function.

**Comment by llaine** [comment]
Okay I understand, then how I can trigger the playing how the music directly without the ion-play directive but with my ng-click function?

**Comment by arielfaur** [comment]
Hmmm.. wouldn't that piece of code toggle playback of a specific track each time you click on the button? Isn't that what it's supposed to do? Or maybe I misunderstood what you're trying to do.

**Comment by llaine** [comment]
What i'm trying to do here, is to manually assign the track using my `playTrack` function.
Because, for instance if I put a $timeout into my controller which will re-assign the `dynamicTrack` after a certain time.
The song will never start. And when I put `togglePlayback =!togglePlayback` it's going to start the song many twice.

**Comment by arielfaur** [comment]
I think it is indeed a bit hacky. I wanted to implement the playlist functionality but I didn't find the time, and this approach you are trying seems hacky as you said. I would have to download your code and try it myself but I am busy at the moment.

**Comment by llaine** [comment]
Okay, any workaround on this that could help me ? I really need to implement it (no time unfortunately).

**Comment by arielfaur** [comment]
Hi! I found some time to fork your project and made a new branch, you can merge it. I made some changes and the dynamic assignment seems to work well now, also the playlist works:
https://github.com/arielfaur/room-guide/tree/fix-dynamic-track

One important thing. There is a bug in the cordova-plugin-media version 2.1.0 you are running therefore the dynamic track was failing. 
You need to update it:
```
cordova plugin rm cordova-plugin-media
cordova plugin add cordova-plugin-media@2.2.0
```

**Comment by llaine** [comment]
Okay dude, thank you very much for that !!!

**Comment by arielfaur** [comment]
So, how did it work?

**Comment by llaine** [comment]
yes looks like it working !

**Comment by miniportal** [comment]
Please, I'm having the same problem.

How can I solve that?

My template:

`        <ion-audio-track track="dynamicTrack" toggle-playback="togglePlayback">
          <ion-audio-controls>
            <div id="audio-button-bar3" class="button-bar">
              <button id="audio-button19" ng-click="shuffle()" class="button button-dark button-small button-block button-clear icon ion-shuffle" ng-class="{btn_branco: playerOptions.shuffle}"></button>
              <button id="audio-button22" ng-click="skipB()" class="button button-dark button-large button-block button-clear icon ion-ios-skipbackward"></button>

              <a class="button button-icon icon button-dark button-large button-block button-clear" ion-audio-play></a>
              
              <button id="audio-button21" ng-click="skipF()" class="button button-dark button-large button-block button-clear icon ion-ios-skipforward"></button>
              <button id="audio-button23" ng-click="loop()" class="button button-dark button-small button-block button-clear icon ion-loop" ng-class="{btn_branco: playerOptions.loop}"></button>
            </div>
          </ion-audio-controls>
        </ion-audio-track>`

My Controller:

`			$scope.dynamicTrack = {
				    url: item.audio[0].CAMINHO,
				    artist: 'Playlegis',
				    title: item.audio[0].NOME,
				    art: item.audio[0].img
				};

			$scope.togglePlayback = !$scope.togglePlayback;`
