### ISSUE TITLE
current time in progress bar start in "-1" not "0"

### ISSUE THREAD

**Issue by nuruddinbadawi** [arielfaur/ionic-audio#56]
I have an audio file but there is a decrease in the current time in the progress bar, I print it what the values in track object I see duration: -1 , status : 0 , progress : 0 ,  URL : "cdvfile://..."

**Comment by arielfaur** [comment]
That is the default value returned by the plugin when duration is unknown. Sometimes the plugin is unable to obtain the track duration. You should hide the value if it's < 0

**Comment by nuruddinbadawi** [comment]
how i can hide the value  ?

**Comment by arielfaur** [comment]
Using angular directives such as ```ng-if``` or ```ng-show```, something like
```
<ion-audio-progress-bar track="track" display-time ng-if="track.duration > 0"></ion-audio-progress-bar>
```

**Comment by nuruddinbadawi** [comment]
thank but ng-if not work you need ng-show 👍

**Comment by nuruddinbadawi** [comment]
but the main problem is finish audio but progress bar not right like in the image 

<img width="443" alt="screen shot 2016-06-11 at 13 10 20" src="https://cloud.githubusercontent.com/assets/5736522/15984500/0febf846-2fd6-11e6-83a6-1d1dc2f32c13.png">

**Comment by arielfaur** [comment]
That is weird. What type of audio are you playing?

**Comment by nuruddinbadawi** [comment]
.mp3

**Comment by nuruddinbadawi** [comment]
@arielfaur  I try your example, I see the same problem like you see in image down, the audio is finished But the **time and progress not compleated**  still like this.

you know what's the problem ?

<img width="438" alt="screen shot 2016-10-04 at 11 16 14" src="https://cloud.githubusercontent.com/assets/5736522/19066913/67f4dfb4-8a24-11e6-9591-c70219fd198d.png">

**Comment by ronisaha** [comment]
Any update on this issue, I'm facing same problem

**Comment by arielfaur** [comment]
Yes, i have seen that before. I believe it is related to the rounding applied while converting position to mm:ss values. You could play around with the angular filter used to convert values and see if you can fix that. I really don't have time to focus on v1 anymore.

**Comment by tbergeron** [comment]
Is this resolved? Can we close this issue?
