### ISSUE TITLE
Is it possible to catch event on completion?

### ISSUE THREAD

**Issue by Snodvod** [arielfaur/ionic-audio#58]
I want to check when my track has finished playing, couldn't find it in your docs but I guess this should be possible?

**Comment by arielfaur** [comment]
Are you on Ionic 1 or 2?

**Comment by Snodvod** [comment]
1

**Comment by arielfaur** [comment]
It isn't implemented yet, although there is a listener for that. I'll try to do that when I find time hopefully this week!

**Comment by Snodvod** [comment]
Is there a possibility I can get that listener to fire an event? Because I've been lookin' in your files and found that onCompletion function, I'm writing the app only for Android

**Comment by arielfaur** [comment]
A quick patch would be to add a ```$rootScope.broadcast``` following this line in order to trigger an event when playback finishes:
https://github.com/arielfaur/ionic-audio/blob/master/src/directives/ion-audio-track.js#L39

Note: that will also trigger if you call ```MediaManager.stop()```

**Comment by arielfaur** [comment]
You would have to rebuild sources with ```gulp build``` to generate the dist versions (uncompressed and minified inside /dist)

**Comment by Snodvod** [comment]
Aright, that works, and where is your 'track is loaded and started playing event?

**Comment by Snodvod** [comment]
update: I found that one and it's inside ion-audio-controls, but I can't get the $rootScope required in the directive...

**Comment by arielfaur** [comment]
To listen for the track loaded event you could do the same and use ```$rootScope.$broadcast``` after this line:
https://github.com/arielfaur/ionic-audio/blob/master/src/directives/ion-audio-controls.js#L28

I guess it should work!

**Comment by Snodvod** [comment]
I don't know why but, after requiring `$rootScope` in the directive declaration I can't capture the broadcasted event in my code. The other one works fine...

**Comment by arielfaur** [comment]
Have you run ```gulp build``` ? 
And I guess you are using ```ion-audio-controls``` in your templates, too. Basic questions :smile:

**Comment by Snodvod** [comment]
Yes, I first tried gulp build but had to do an npm install, after that gulp build ran fine. I am indeed using ion-audio-controls :)

**Comment by arielfaur** [comment]
Sorry wrong line!
It's after this line that you need to add the ```$rootScope``` statement:
https://github.com/arielfaur/ionic-audio/blob/master/src/directives/ion-audio-controls.js#L33

I don't know if that changes anything.

**Comment by Snodvod** [comment]
I've tried it over there too... seems like the rootScope doesn't get $broadcasted

**Comment by arielfaur** [comment]
I ran out of ideas, sorry!

**Comment by Snodvod** [comment]
That's a pitty haha ;)

**Comment by marcusforsberg** [comment]
Any chance of seeing this implemented in the near future? :) I would do a PR but I'm uncertain as to how it's best done for an Ionic plugin (newbie here!).

**Comment by lync0056** [comment]
@marcusforsberg Not sure why they were having issue previous, but it works for me inside the startTimer function. 
![screen shot 2016-08-05 at 2 48 27 pm](https://cloud.githubusercontent.com/assets/15604237/17426949/fbe11f7c-5b1b-11e6-9e34-6d93e9e33d19.png)

**Comment by marcusforsberg** [comment]
@lync0046 Ah, sorry, I missed that this thread was about the Ionic 1 version. I'm running the Ionic 2 version and it doesn't seem to broadcast any events at all at this point.

**Comment by tbergeron** [comment]
Any updates on this issue? Is this resolved?
