### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by jokandre** [arielfaur/ionic-audio#59]
I would like to ask how can I help updating the documentation. 

1. gulpfile.js snippets outdated. Will cause gulp to fail because main.d.ts file does not exist.
Workaround: rename main.d.ts to index.d.ts 

2. In app.ts highlight:
import {Type, provide} from '@angular/core';  
Also '@angular/core' instead of 'angular2/core'

After starting a brand new project these were the problems I had to solve after following the doc instructions.

**Comment by bkitaec** [comment]
+1

**Comment by arielfaur** [comment]
Hi @jokandre 
Sorry for the delay! I haven't yet updated the plugin to Ionic 2 Beta 10. I will then resolve any issues.

**Comment by arielfaur** [comment]
@jokandre I have updated the plugin to work with ionic2 beta 10 and also fixed the documentation. Thanks for the heads up.
