### ISSUE TITLE
Cordova Media Plugin With Compression

### ISSUE THREAD

**Issue by lync0056** [arielfaur/ionic-audio#61]
Hi,

Do you foresee any issue if I were to integrate the Cordova-Media-Plugin-With-Compression extension rather than the original Media plugin into this module?

I have circumstances where audio file size is going to be an issue.

Thank you in advance.

Cameron

https://github.com/remoorejr/cordova-plugin-media-with-compression

**Comment by arielfaur** [comment]
Hi @lync0056 
I don't see any reason why this wouldn't work, especially since it is an extension of the standard plugin. I guess that means the class methods remain the same so it should be fine.

**Comment by arielfaur** [comment]
By the way, are you on v1 or v2?

**Comment by lync0056** [comment]
V1.

Ok, thank you. I will give it a go.
