### ISSUE TITLE
Every track I select/play is the same audio file when simulating ios

### ISSUE THREAD

**Issue by tjohnson5** [arielfaur/ionic-audio#62]
Hello! I'm running into a strange issue that I can't quite figure out.

So I'm using Ionic V2 and version 2 of this plugin to play audio off of a podcast JSON feed that I'm pulling in. Looks and works perfectly fine when I do "ionic serve" and test in browser - every track I press play on plays the proper .mp3 file. However, when I run "ionic emulate ios", it all looks perfect, but every track that I press "play" on just plays the same single audio file. And if I pause and click another track, it just picks up where the same audio left off. 

I see in the console its writing "Loading track abc.mp3" and "Playing track abc.mp3" - which is the corresponds correctly with the track I'm selecting. But that isn't the actual file that's being played. The actual file that keeps being played (no matter which track I "choose") is the very last .mp3 that comes in my feed. 

Any idea what could be causing this? Perhaps you've seen such an issue before... 

I'd appreciate any direction!

**Comment by arielfaur** [comment]
This is weird. I've never experienced that.  Have you tried on an actual device?

**Comment by tjohnson5** [comment]
No I have not yet tried on the actual device. Perhaps I can give that a shot and hope its just the simulator being wacky :)

But if you or anyone else have any other tips/ideas in the meantime, they'd be welcome!

Thanks

**Comment by arielfaur** [comment]
Are you by any chance using the "track by" syntax of ```*ngFor```?

**Comment by tjohnson5** [comment]
No I'm doing something like _*ngFor="let podcast of podcasts"_ 

I am somewhat new to this Ionic and Angular stuff so I'm not dismissing the fact that I may just be doing something the complete wrong way. I pretty much copied your examples and instructions exactly

**Comment by arielfaur** [comment]
Don't worry. I need to update the bundled sample project to the latest Ionic 2 release. I will see if there are any issues and get back to you then.

**Comment by tjohnson5** [comment]
Much appreciated! I'll keep messing with it in the meantime.

**Comment by arielfaur** [comment]
I have updated the bundled sample project to the work with the latest ionic 2 release. Have you managed to get it working?

**Comment by tjohnson5** [comment]
Ok thanks. I'll check that out here soon. 

But no I haven't gotten it yet. I have tested it on the actual device and the issue still remains. Strange that it works properly in the browser but not iOS simulator or on the device.

**Comment by tjohnson5** [comment]
Just pulled down your latest and it runs just fine... I must have set up my project incorrectly somehow. Not sure what I could have done to have that issue... You think any of your updates could have addressed the issue?

**Comment by arielfaur** [comment]
It could have been related to one of the issues addressed by the latest Angular2/Ionic2 release. But I wouldn't know for sure. I will close this for now. If you see any issues let me know.
