### ISSUE TITLE
Issue with "Seek To" with multiple progress bars

### ISSUE THREAD

**Issue by ccravens** [arielfaur/ionic-audio#63]
We use ng-repeat to display multiple audio progress bars on a single page. The problem is, within the "ionAudioProgressBar" directive, you have a template definition where on-release is assigned to the scoped sliderRelease() function:

``` javascript
            template:
                '<h2 class="ion-audio-track-info" ng-style="displayTrackInfo()">{{track.title}} - {{track.artist}}</h2>' +
                '<div class="range">' +
                '<ion-audio-progress track="track"></ion-audio-progress>' +
                '<input type="range" name="volume" min="0" max="{{track.duration}}" ng-model="track.progress" on-release="sliderRelease()" disabled>' +
                '<ion-audio-duration track="track"></ion-audio-duration>' +
                '</div>',
```

and the sliderRelease() function:

``` javascript
                scope.sliderRelease = function() {
                    var pos = scope.track.progress;
                    MediaManager.seekTo(pos);
                };
```

If we release on ANY of the progress bars in our list, it resets the audio for the track that is currently playing whether or not the progress bar that got the release event is associated with the currently playing track or not. Our temp fix is this:

``` javascript
                scope.sliderRelease = function() {
                    var pos = scope.track.progress;
                    if(pos > 0) {
                        MediaManager.seekTo(pos);
                    }
                };
```

Which would prevent a user from sliding the position all the way back to zero, however it sure beats reseting the track anytime a slider progress bar is touched while scrolling up and down for example. Is there a better way to determine in the directive if it is associated with the currently playing track? Didn't want to necessarily submit a PR with our little if() hack above. Thanks!

**Comment by arielfaur** [comment]
I am not sure I understand your use case. Why do you need multiple progress bars? Each progress bar should be nested within a ```ion-audio-track``` directive, is that your case? 
Maybe you can share your view template.

**Comment by ccravens** [comment]
We have multiple progress bars because we are displaying multiple playable tracks within the same page (a common use case I assume).

Our view template looks as follows:

```
   <ion-list>
      <ion-item class="trackRepeat" ng-repeat="talk in talks track by talk._id">
          <ion-audio-track track="talk">
              <div class="talkContainer">
                    <span class="talkText" ng-bind="talk.text"></span>
                    <ion-audio-controls>
                      <ion-spinner icon="ios"></ion-spinner>
                      <a class="button button-icon icon playButton" ion-audio-play></a>
                      <ion-audio-progress-bar display-time></ion-audio-progress-bar>
                    </ion-audio-controls>
              </div>
          </ion-audio-track>
   </ion-list>
```

It renders a list of multiple tracks we can play on one page. Thanks!

**Comment by arielfaur** [comment]
Hi @ccravens 
Yes, that's perfect, with one minor remark: can you try removing the "by talk._id" from the ```ng-repeat``` and see if that fixes the problem?

**Comment by arielfaur** [comment]
@ccravens any update on this?

**Comment by tbergeron** [comment]
With Ionic2 there's no seekTo() function. How do we seek with the new version?

**Comment by tbergeron** [comment]
Any news from original poster?

**Comment by tbergeron** [comment]
Trying once again :P any update @ccravens ?
