### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by BrettKoenig** [arielfaur/ionic-audio#64]
Hello, I'm getting a few errors in my console and the audio won't play in Ionic View. The errors are:

Error
"ionic-audio: missing Cordova Media plugin. Have you installed the plugin? 
Run 'ionic plugin add cordova-plugin-media'" 
and  
Cannot read property 'stop' of null
    at ion-audio.min.js:320

I've already ran: cordova plugin add cordova-plugin-media

I know it won't work with Ionic Serve in the browser, but the audio won't run on my iPhone either. The project is at https://github.com/BrettKoenig/h2oApplication if you'd be willing to take a look that'd be awesome!

Thanks!

**Comment by arielfaur** [comment]
@BrettKoenig I have just cloned your project and whenever I try to run it I guess an exception. It seems one file is missing in the project tree. Take a look at the screenshot.

![capture](https://cloud.githubusercontent.com/assets/3749268/17143596/32e19ea6-532a-11e6-91c9-00ccffe9a030.JPG)

**Comment by BrettKoenig** [comment]
Hey. Thanks for the reply! I should have told you, I removed that file for
security. It has some keys in it. Do you have an email I could send it to
you at?

**Comment by arielfaur** [comment]
Check out my GitHub profile, it is there :smile:
