### ISSUE TITLE
Android - Error on playing audiostream (v1)

### ISSUE THREAD

**Issue by keodeveloper** [arielfaur/ionic-audio#69]
Hi, I get an error when trying to play a radiostream (not real url in code below).. The stream is playing in iOS (but can't stop it... get the #40 issue there).... 

ionic-audio 1.3.1
cordova-plugin-media 2.3.0

Here is the Android Studio log:

I/chromium: [INFO:CONSOLE(152)] "ionic-audio: playing track Radiostream", source: file:///android_asset/www/lib/ionic-audio/dist/ion-audio.js (152)
W/PluginManager: THREAD WARNING: exec() call to Media.create blocked the main thread for 28ms. Plugin should use CordovaInterface.getThreadPool().
I/MediaPlayer: Need to enable context aware info
V/MediaPlayer-JNI: native_setup
V/MediaPlayer: constructor
V/MediaPlayer: setListener
V/MediaPlayer-JNI: setAudioStreamType: 3
V/MediaPlayer: MediaPlayer::setAudioStreamType
V/MediaPlayer: setVideoSurfaceTexture
V/MediaPlayer: prepareAsync
D/MediaHTTPConnection: setReadTimeOut =  30000ms
W/PluginManager: THREAD WARNING: exec() call to Media.startPlayingAudio blocked the main thread for 33ms. Plugin should use CordovaInterface.getThreadPool().
D/MediaHTTPConnection: setReadTimeout with 30000ms
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/MediaHTTPConnection: response code = 200
V/MediaHTTPConnection: mTotalSize is 60
V/MediaPlayer: message received msg=100, ext1=1, ext2=-2147483648
E/MediaPlayer: error (1, -2147483648)
V/MediaPlayer: callback application
V/MediaPlayer: back from callback
E/MediaPlayer: Error (1,-2147483648)

---- Controller --------------------------------------------------------------------

.controller('MyController', function($scope, $ionicPlatform, MediaManager) {
  var url = 'http://myurl.com:9999/listen.m3u?sid=1';
  $ionicPlatform.ready(function() {
     $scope.mytrack = {
      url: url,
      artist: 'Artist Name',
      title: 'Radio Stream',
      art: 'img/my_img.png'
    }
  });
})

---- HTML (?some tags don't display?... ion-audio-track track="mytrack"... div.list-inset etc ) ---

<ion-audio-track track="mytrack">

  <div class="list list-inset">
    <div class="item item-thumbnail-left">

```
  <img ng-src="{{mytrack.art}}">
  <h2>{{mytrack.title}}</h2>
  <p>{{mytrack.artist}}</p>

  <ion-audio-controls>
    <a class="button button-icon icon" ion-audio-play></a>
    <ion-spinner icon="ios"></ion-spinner>
  </ion-audio-controls>

</div>

<div class="item">
  <ion-audio-progress-bar track="mytrack" display-time></ion-audio-progress-bar>
</div>
```

  </div>

</ion-audio-track>

**Comment by arielfaur** [comment]
@keodeveloper I think this has been already mentioned somewhere. The Cordova Media plugin does not support all audio formats and until recently did not support streaming either. I don't know the reason why.

**Comment by gmapis** [comment]
Hey @keodeveloper  
did you ever figure this out? I'm having a similar issue. I'm able to stream m3u in ios, but not android. 
I'm using ionic 2 (ionic-native v2.4.1)

**Comment by tbergeron** [comment]
Any reply from OP? Inactive issue? Can we close this?
