### ISSUE TITLE
ionic-audio, ios, local mp3 file, not playng 

### ISSUE THREAD

**Issue by ansaril3** [arielfaur/ionic-audio#71]
Hi! Thanks for player!
 I found problem, when I trying play local audiofile on IOS devices.
File destination: /www/build/audio/1.mp3 (copy files into /www with gulp task)
In .ts component I write link:  ... 'audio': 'build/audio/1.mp3', ...

When I using some internet link ( ... 'audio': 'https://archive.org/download/JM2013-10-05.flac16/V0/jm2013-10-05-t12-MP3-V0.mp3',  ...), or run in Android device/ionic serve, it works fine.

**Comment by arielfaur** [comment]
I guess you need to set the proper path for your audio files in your device. These are different for Android and iOS

**Comment by vintots** [comment]
@arielfaur  is right , i encountered also this error in IOS, because the path that i have in my local url contains 'file://' on its prefix , I solved it by replacing the 'file://' in the path, and the player works fine
