### ISSUE TITLE
Question: Is there a way to reset all the state of the $scope.playback.tracks values specially (onSuccess,onStatusChange,onProgress,status,duration,progress) for the audio to play again i am using Ionic V1

### ISSUE THREAD

**Issue by vintots** [arielfaur/ionic-audio#75]

**Comment by vintots** [comment]
I tried to override the values of some of its properties 
 $scope.tracks[index].progress = 0;
  $scope.tracks[index].status = 0;
  $scope.tracks[index].duration = -1;

but the ion audio detect that the track is already finished,

**Comment by arielfaur** [comment]
Those variables should reset once playback is finished. What are you trying to achieve?

**Comment by tbergeron** [comment]
Inactive issue? Can we close this?

**Comment by vintots** [comment]
yes , :)
