### ISSUE TITLE
Is there possibility to play songs one after another continuously?

### ISSUE THREAD

**Issue by mrbankim** [arielfaur/ionic-audio#79]
Is there possibility to play songs one after another continuously?

**Comment by arielfaur** [comment]
no, not yet. i know this should be a core feature but i don't have time now. also, i am not able to maintain v1 anymore. i will focus on v2 mostly!

**Comment by tbergeron** [comment]
Just for reference, these are also on the same topic:
https://github.com/arielfaur/ionic-audio/issues/122
https://github.com/arielfaur/ionic-audio/issues/114
https://github.com/arielfaur/ionic-audio/issues/88

I guess we could close a few of them some day lol

**Comment by arielfaur** [comment]
#88
