### ISSUE TITLE
Download locally?

### ISSUE THREAD

**Issue by LittleHamster** [arielfaur/ionic-audio#8]
Is it possible to give the user the option to download the audios locally in order to play them when offline?

**Comment by arielfaur** [comment]
That would be a really nice feature. But I feel it's out of the scope of this module right now. Maybe as an optional plugin but there are other features in the pipeline to do and I am the only maintainer so far. I will keep that in mind anyway :)

**Comment by ascendedmasta** [comment]
There's a couple of cordova plugins Ive used for android that will save a file to a folder in memory. You can program a way for your app to drill down to the folder/s add them to a list and use ionic-audio to play individual files. Could be useful for hearing back lectures, and such.

**Comment by arielfaur** [comment]
That's an interesting point. I have also used the Cordova File plugin and the other one to download files. One question @ascendedmasta , do you know if there is a reliable plugin to encypt those files and prevent the user from directly accessing them outside the app?

**Comment by ascendedmasta** [comment]
I haven't done that. I know that each app declares a folder in storage where you can place files that will only be used by that app. On iOS I know this generally can't be accessed, but android give you unlimited access to App Folders and you could, in throry grab that audio file and move, copy, or delete it.

**Comment by leonardosalles** [comment]
Hi,

I already used  (this plugin)[https://github.com/sgrebnov/cordova-plugin-background-download] before and it encrypt the file, so you cannot access file directly. I am not sure if it is hard secure because I guess the plugin using something like MD5 to encrypt but is better than nothing.

**Comment by jnthnschlt** [comment]
download-feature would be aweseome!! :-)

**Comment by tbergeron** [comment]
As @arielfaur mentioned this feature sounds really out-of-scope.
This should be handled by application code and not this package as this includes all kind of little details that would be hard to document on a per configuration basis.

I'm currently implementing this feature but within my app, not within the package itself and I suggest OP and commenters to do the same.

IMO we should close this issue.

**Comment by arielfaur** [comment]
Yes, no time for this now. Unless any of you want to own the taks 😄
