### ISSUE TITLE
how to ignore undefined/unsupportable track

### ISSUE THREAD

**Issue by anilkumarsoni** [arielfaur/ionic-audio#80]
hey arielfaur,
please help me in following..
how to ignore undefined/unsupportable track. also i am not able to pause current audio playing.

this is my code--
<ion-audio-track class="item item-avatar bg-transparent border_white" style="padding:8px;" ng-repeat="track in postData" track="track">
        <img src="img/user-icon.png" class="container" style="float: left;width: 27%;border-radius: 100%;margin: 14px 0 14px 0px;">
        <ion-audio-controls>
        <h2 style="padding: 8px 5px 8px 0px;">{{track.artists || 'unknown'}}</h2>
          <button style="margin: 5px !important;position: absolute;right: 0px;" class="button button-small button-assertive icon-left" ion-audio-play text-play="Play" text-pause="Pause">play/pause</button>
        </ion-audio-controls>
      </ion-audio-track> 

thanks in advance !

**Comment by tbergeron** [comment]
Hi, I'm not the repository owner but I'm trying to help out as I need to use this package too so I'm doing my best to iron out the remaining issues. I've started to check out the opened issues. There are lots of doubles without any examples whatsoever. I'd like to do some clean up, so first I need to make sure the opened issues are legitimate.

**Please make sure to follow these simple guidelines in the future:**

1) Use the GitHub issue search — check if the issue has already been reported. Check if the issue has been fixed.

2) If none is found, create a new issue by describing your problem, providing example of the boggus code and also make sure to write it with proper syntax and syntax. Re-read your issue twice or more to make sure it will makes sense to the repository owner. He might not even reply if he doesn't understand what's the problem.

A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
> 
> A summary of the issue and the browser/OS environment in which it occurs. If suitable, include the steps required to reproduce the bug.
> 
> This is the first step
> This is the second step
> Further steps, etc.
> <url> - a link to the reduced test case
> 
> Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, and potential solutions (and your opinions on their merits).

Once a proper issue description is provided, we will be way more prepared to help you out. Thanks a lot and have a nice day.
