### ISSUE TITLE
How to use native audio

### ISSUE THREAD

**Issue by sjosen** [arielfaur/ionic-audio#84]
Hello

First of all, thanks for providing this plugin.

No matter what I do it loads the WebAudioProvider from the factory. I have installed cordova-plugin-media. I have tried with both ionic view app and building with xcode.

Any ideas?

**Comment by arielfaur** [comment]
@sjosen Have you built the demo project included? Is it not working with native audio either?

**Comment by sjosen** [comment]
I get native audio with Android and html audio in iOS. Html audio is working fine though, so perhaps it doesn't matter. I was just wondering :)

**Comment by arielfaur** [comment]
I haven't had the chance to test on iOS. Still having trouble?

Just upgraded the module to Ionic 2 final.  See http://arielfaur.github.io/ionic-audio/2.0/index.html

**Comment by tbergeron** [comment]
Is this still occurring? Otherwise can we close this issue?

**Comment by sjosen** [comment]
I can test it soon. I can open a new issue if it's still a problem
