### ISSUE TITLE
Android Cordova - Exit the app, error message "Unfortunately, example-audio has stopped" 

### ISSUE THREAD

**Issue by devshisiyani** [arielfaur/ionic-audio#87]
Android version: 6.0.1
Cordova version:6.0.0
Device Samsung s6
Built using IONIC 2

Installed the app example app (Ionic Audio for Angular/ionic 2) on the Samsung device and run up the app. This works fine when you play music and pause/stop the music.

Sometimes when you hit  backbutton ( to exit app) you get the error "Unfortunately, example-audio has stopped" 

This occurs when you play the music and then select pause the music.
The error is not consistently repeatable but occurs once out of five attempts when you exit the app.

No change to the code has been made. Just repo and built using ionic 2

cordova Plugins used :
"cordova-plugin-console": "1.0.5",
    "cordova-plugin-device": "1.1.4",
    "cordova-plugin-compat": "1.1.0",
    "cordova-plugin-file": "4.3.1",
    "cordova-plugin-media": "2.4.1",
    "cordova-plugin-splashscreen": "4.0.1",
    "cordova-plugin-statusbar": "2.2.1",
    "cordova-plugin-whitelist": "1.3.1",
    "ionic-plugin-keyboard": "2.2.1"

If you need more infor let me know.

**Comment by arielfaur** [comment]
Can you give it a try. I refactored the module to work with Ionic 2 final.

Updated docs : http://arielfaur.github.io/ionic-audio/2.0/index.html

**Comment by tbergeron** [comment]
Did original poster retried this? Is this still occuring? Can we close this issue?
