### ISSUE TITLE
cordova media freezes ui

### ISSUE THREAD

**Issue by mikeblakeney** [arielfaur/ionic-audio#9]
One issue I ran into with doing a similar module was that when I loaded a network audio file, the entire UI freezes until it's ready to play.  I tried to figure out a way to display an $ionicLoading indicator, but because the entire UI freezes before the indicator appears nothing gets displayed.  Anyway, I was just wondering if this has a solution for that use case?

**Comment by arielfaur** [comment]
Yes, the module displays a loading spinner `<ion-spinner>` instead of $ionicLoading.  Have you tried the module yet?

**Comment by mikeblakeney** [comment]
not yet.  I've already coded a media player with cordova and was digging for solutions to the whole UI freezing.  If I can get that fixed then I just need to style it up and I'm good to go.  Sounds like this plugin is definitely worth exploring more.  Thanks!

**Comment by arielfaur** [comment]
Are you using Ionic at all? Because this module relies on Ionic and Angular, as well as the Cordova Media plugin.

**Comment by arielfaur** [comment]
Oh, ignore my last question. I see you are using Ionic. It's late night over here :-)

**Comment by mikeblakeney** [comment]
no worries.  still mid afternoon here, but I know what late nights can do.  lol

**Comment by mikeblakeney** [comment]
I see where you use the ion-spinner.  but I think playback would still freeze the whole UI while it loads the audio...  This is the bug in Media I'm refering to, https://issues.apache.org/jira/browse/CB-1176

**Comment by arielfaur** [comment]
That issue is two years old and it's marked as resolved! I don't see any freezing at all. In fact, I just opened the app and played media hosted on Amazon S3, while the track was loading I could switch tabs. No freezing. I tried it on my Nexus 7 running Android 5. 
Simply check out this project, install dependencies and run on your device. Let me know if you see any issues!

**Comment by mikeblakeney** [comment]
I didnt even see it was marked resolved.  Got the monitor glaze going.  Thanks again.  If I get the time, I'll run it on a device to check it out.
